export function EpisodeSelector({ currentEpisode, totalEpisodes, onSelectEpisode, progress = [] }: { currentEpisode: number; totalEpisodes?: number | null; onSelectEpisode: (episode: number) => void; progress?: Array<{ episodeNumber: number; percentage: number; completed: boolean }> }) {
  const total = totalEpisodes && totalEpisodes > 0 ? totalEpisodes : null;
  const max = total ?? Math.max(currentEpisode + 9, 10);
  const size = max > 50 ? 50 : max;
  const start = max > 50 ? Math.floor((currentEpisode - 1) / 50) * 50 + 1 : 1;
  const end = Math.min(start + size - 1, max);
  const ranges = total ? Array.from({ length: Math.ceil(total / 50) }, (_, i) => ({ start: i * 50 + 1, end: Math.min((i + 1) * 50, total) })) : [];
  return <section aria-label="Episodes">
    <div className="mb-3 flex flex-wrap items-center justify-between gap-2"><h2 className="text-lg font-bold text-foreground">Episodes</h2>{ranges.length > 1 && <div className="flex flex-wrap gap-1">{ranges.map((range) => <button type="button" key={range.start} onClick={() => onSelectEpisode(Math.max(range.start, Math.min(currentEpisode, range.end)))} className={`rounded px-2 py-1 text-xs font-semibold ${currentEpisode >= range.start && currentEpisode <= range.end ? "bg-accent/20 text-foreground" : "text-muted hover:text-foreground"}`}>{range.start}–{range.end}</button>)}</div>}</div>
    <div className="grid grid-cols-5 gap-2 sm:grid-cols-10 md:grid-cols-12">{Array.from({ length: end - start + 1 }, (_, index) => start + index).map((episode) => { const item = progress.find((entry) => entry.episodeNumber === episode); return <button type="button" key={episode} aria-current={episode === currentEpisode ? "true" : undefined} aria-label={`Episode ${episode}${item?.completed ? ", completed" : item && item.percentage > 0 ? ", in progress" : ""}`} onClick={() => onSelectEpisode(episode)} className={`relative min-h-10 rounded-md border text-sm font-bold transition focus:outline-none focus:ring-2 focus:ring-accent ${episode === currentEpisode ? "border-accent bg-accent text-background" : "border-outline bg-surface text-muted hover:text-foreground"}`}>{episode}{item?.completed ? <span aria-hidden="true" className="absolute right-1 top-0 text-[10px]">✓</span> : item && item.percentage > 0 ? <span aria-hidden="true" className="absolute bottom-1 left-1 right-1 h-0.5 rounded bg-accent" style={{ width: `${Math.max(10, item.percentage)}%` }} /> : null}</button>; })}</div>
  </section>;
}
