import {expect,test} from '@playwright/test';
import {randomUUID} from 'node:crypto';
import {token,users} from '../e2e/test-auth';
test('isolated cloud library paging persistence and A/B privacy',async({page,request})=>{
 const prefix='Cloud library '+randomUUID().slice(0,8),id=820001;const header={Authorization:'Bearer '+token(users[0],'a@example.com')};
 await page.route('https://auth.test/**',async route=>{if(route.request().url().includes('logout'))return route.fulfill({status:204,body:''});const email=route.request().postDataJSON()?.email??'a@example.com',owner=users[email.startsWith('b')?1:0];return route.fulfill({json:{access_token:token(owner,email),token_type:'bearer',expires_in:3600,expires_at:Math.floor(Date.now()/1000)+3600,refresh_token:randomUUID(),user:{id:owner,aud:'authenticated',role:'authenticated',email,app_metadata:{provider:'email'},user_metadata:{},created_at:'2025-01-01T00:00:00.000Z'}}});});
 async function login(email:string){await page.goto('/login');await page.getByLabel('Email',{exact:true}).fill(email);await page.getByLabel('Password',{exact:true}).fill(randomUUID());await page.getByRole('button',{name:'Sign In',exact:true}).click();await expect(page.getByRole('link',{name:'Profile',exact:true})).toBeVisible();}
 try{expect((await request.post('/api/favorites',{headers:header,data:{anilistId:id,title:prefix,genres:['Action']}})).status()).toBe(201);await login('a@example.com');await page.goto('/favorites?search='+encodeURIComponent(prefix));await expect(page.getByText('1 results',{exact:true})).toBeVisible();await expect(page.getByText(prefix,{exact:true})).toBeVisible();await page.getByRole('button',{name:'list',exact:true}).click();await page.reload();await expect(page.getByRole('button',{name:'list',exact:true})).toHaveAttribute('aria-pressed','true');await expect(page.getByText(prefix,{exact:true})).toBeVisible();await page.goto('/profile');await page.getByRole('button',{name:'Sign out',exact:true}).first().click();await login('b@example.com');await page.goto('/favorites?search='+encodeURIComponent(prefix));await expect(page.getByText('0 results',{exact:true})).toBeVisible();await expect(page.getByText(prefix,{exact:true})).toHaveCount(0);
 }finally{await request.delete('/api/favorites/'+id,{headers:header});}
});
