import { act, render, screen, waitFor } from '@testing-library/react';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { useHomeSummary } from './useHomeData';
import { homeApi, type HomeSummary } from '../services/homeApi';
const state = vi.hoisted(() => ({ auth: { mode: 'local', loading: false, user: null as { id: string } | null }, library: { loading: false, revisions: { favorites: 0, watchlist: 0, 'recently-viewed': 0, 'continue-watching': 0, 'recently-completed': 0 } } }));
vi.mock('../auth/AuthContext', () => ({ useAuth: () => state.auth }));
vi.mock('../context/LibraryContext', () => ({ useOptionalLibrary: () => state.library }));
vi.mock('../services/homeApi', () => ({ homeApi: { get: vi.fn() } }));
const data = (name = 'Local Name'): HomeSummary => ({ profile: { status: 'ready', data: { displayName: name } }, personalized: { status: 'ready', data: { recommendations: [], continuations: [], because: null, favoriteGenres: null, audience: 'cold', meta: { personalized: false, partial: false, failedSources: 0 } } } });
function Probe() { const h = useHomeSummary(); return <><p>{h.data?.profile?.data?.displayName}</p><p>{h.error}</p><p>{h.slow ? 'Slow' : ''}</p><button onClick={h.retry}>Retry</button></>; }
describe('identity-safe focused Home summary', () => {
  beforeEach(() => { vi.clearAllMocks(); state.auth = { mode: 'local', loading: false, user: null }; for (const key of Object.keys(state.library.revisions)) state.library.revisions[key as keyof typeof state.library.revisions] = 0; vi.mocked(homeApi.get).mockResolvedValue(data()); });
  it('loads one compact bundle and preserves greeting on focused refresh', async () => { const { rerender } = render(<Probe />); await screen.findByText('Local Name'); expect(homeApi.get).toHaveBeenCalledTimes(1); vi.mocked(homeApi.get).mockResolvedValue({ personalized: data().personalized }); state.library.revisions.favorites++; rerender(<Probe />); await waitFor(() => expect(homeApi.get).toHaveBeenLastCalledWith(expect.any(AbortSignal), 'personalized')); expect(screen.getByText('Local Name')).toBeVisible(); act(() => window.dispatchEvent(new Event('aniverse:progress-changed'))); await waitFor(() => expect(homeApi.get).toHaveBeenLastCalledWith(expect.any(AbortSignal), 'activity')); });
  it('never calls private Home while signed out', async () => { state.auth.mode = 'supabase'; render(<Probe />); await new Promise(r => setTimeout(r, 150)); expect(homeApi.get).not.toHaveBeenCalled(); });
  it('ignores delayed A data after switching to B and aborts A', async () => { let resolve!: (d: HomeSummary) => void; state.auth = { mode: 'supabase', loading: false, user: { id: 'a' } }; vi.mocked(homeApi.get).mockImplementationOnce(() => new Promise(r => { resolve = r; })).mockResolvedValue(data('B Name')); const { rerender } = render(<Probe />); await waitFor(() => expect(homeApi.get).toHaveBeenCalledTimes(1)); const signal = vi.mocked(homeApi.get).mock.calls[0][0]; state.auth.user = { id: 'b' }; rerender(<Probe />); await screen.findByText('B Name'); act(() => resolve(data('A Name'))); expect(signal.aborted).toBe(true); expect(screen.queryByText('A Name')).not.toBeInTheDocument(); state.auth.user = null; rerender(<Probe />); expect(screen.queryByText('B Name')).not.toBeInTheDocument(); });
  it('provides a safe failure and user-triggered retry', async () => { vi.mocked(homeApi.get).mockRejectedValueOnce(new Error('private raw detail')); render(<Probe />); await screen.findByText('Your home is temporarily unavailable. Please retry.'); screen.getByText('Retry').click(); await screen.findByText('Local Name'); expect(homeApi.get).toHaveBeenCalledTimes(2); });
  it('shows a slow-start status without retry storms', async () => { vi.useFakeTimers(); vi.mocked(homeApi.get).mockImplementation(() => new Promise(() => {})); const view = render(<Probe />); await act(async () => { await vi.advanceTimersByTimeAsync(4100); }); expect(screen.getByText('Slow')).toBeVisible(); expect(homeApi.get).toHaveBeenCalledTimes(1); view.unmount(); vi.useRealTimers(); });
});
