import { fireEvent, render, screen } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { HomePage } from './HomePage';
import { useHomeSummary } from '../hooks/useHomeData';
import { useAnimePage } from '../hooks/useAnimePage';
import { animeFixture } from '../test/fixtures';
import type { HomeSummary } from '../services/homeApi';
vi.mock('../hooks/useHomeData'); vi.mock('../hooks/useAnimePage');
const ready = (): HomeSummary => ({ profile: { status: 'ready', data: { displayName: 'தமிழ்' } }, continueWatching: { status: 'ready', data: [] }, recentlyCompleted: { status: 'ready', data: [] }, personalized: { status: 'ready', data: { recommendations: [{ anime: { ...animeFixture, id: 2 }, reason: 'Because you like Action', personalized: true }], continuations: [], because: { sourceAnime: { id: 1, title: 'Naruto' }, recommendations: [{ anime: { ...animeFixture, id: 3 }, reason: 'Because you watched Naruto' }] }, favoriteGenres: { genre: 'Action', recommendations: [{ anime: { ...animeFixture, id: 4 }, reason: 'Because you like Action' }] }, audience: 'established', meta: { personalized: true, partial: false, failedSources: 0 } } } });
function show(data: HomeSummary | null, options = {}) { vi.mocked(useHomeSummary).mockReturnValue({ enabled: true, data, loading: false, error: null, slow: false, retry: vi.fn(), reasons: rows => Object.fromEntries((rows ?? []).map(r => [r.anime.id, r.reason ?? ''])), ...options }); render(<MemoryRouter><HomePage /></MemoryRouter>); }
describe('adaptive Home audience and section isolation', () => {
  beforeEach(() => { vi.clearAllMocks(); vi.mocked(useAnimePage).mockReturnValue({ anime: [animeFixture], loading: false, error: null, pagination: null, retry: vi.fn() }); });
  it('shows public discovery without private wording when signed out', () => { show(null, { enabled: false }); for (const title of ['Trending Now', 'Popular', 'Seasonal', 'Top Rated']) expect(screen.getByRole('heading', { name: title })).toBeVisible(); expect(screen.queryByText(/Welcome back/)).not.toBeInTheDocument(); expect(screen.queryByText(/personalize your home/)).not.toBeInTheDocument(); });
  it('gives cold accounts one unobtrusive CTA and honest catalog fallback', () => { const d = ready(); d.personalized.data!.audience = 'cold'; d.personalized.data!.meta.personalized = false; d.personalized.data!.because = null; d.personalized.data!.favoriteGenres = null; show(d); expect(screen.getByText(/Add favorites or start watching/)).toBeVisible(); expect(screen.getByRole('heading', { name: 'Popular Picks' })).toBeVisible(); expect(screen.queryByRole('heading', { name: 'For You' })).not.toBeInTheDocument(); });
  it('uses modest light-signal copy', () => { const d = ready(); d.personalized.data!.audience = 'light'; show(d); expect(screen.getByText('A few picks based on your recent activity')).toBeVisible(); });
  it('orders established sections deterministically and keeps truthful reasons', () => { show(ready()); expect(screen.getByText('Welcome back, தமிழ்')).toBeVisible(); const titles = screen.getAllByRole('heading', { level: 2 }).map(h => h.textContent); expect(titles.slice(0, 3)).toEqual(['For You', 'Because You Watched Naruto', 'More Action you may like']); expect(screen.getByText('Because you watched Naruto')).toBeVisible(); expect(screen.queryByText(/@/)).not.toBeInTheDocument(); });
  it('suppresses all ready empty personal sections', () => { const d = ready(); Object.assign(d.personalized.data!, { recommendations: [], because: null, favoriteGenres: null }); show(d); expect(screen.queryByRole('heading', { name: 'For You' })).not.toBeInTheDocument(); expect(screen.queryByText('No titles available')).not.toBeInTheDocument(); });
  it('isolates private failure while public discovery remains usable', () => { const d = ready(); d.personalized = { status: 'error', data: null, message: 'Recommendations are temporarily unavailable.' }; show(d); expect(screen.getByRole('heading', { name: 'Trending Now' })).toBeVisible(); fireEvent.click(screen.getByRole('button', { name: 'Try again' })); expect(vi.mocked(useHomeSummary).mock.results[0].value.retry).toHaveBeenCalledOnce(); });
  it('keeps public cards visible during slow private startup', () => { show(null, { loading: true, slow: true }); expect(screen.getByText(/server may be starting up/)).toBeVisible(); expect(screen.getByRole('heading', { name: 'Trending Now' })).toBeVisible(); expect(screen.getByText('Loading your home')).toBeInTheDocument(); });
});
