import { pageLimit, validateSetting } from "../utils/validation.js";
import { Router, type NextFunction, type Response } from "express";
import { z } from "zod";
import type { UserPlaybackRepository } from "../repositories/repository.contracts.js";
import type { AuthenticatedRequest } from "../types/auth.types.js";
import { AppError } from "../utils/appError.js";

const id=z.coerce.number().int().positive(),episode=z.coerce.number().int().positive().max(10000);
const body=z.object({currentTime:z.number().finite().min(0).max(1e7),duration:z.number().finite().positive().max(1e7),providerId:z.enum(["cinextream","yenime","zokoanime"]).nullable().optional(),language:z.enum(["sub","dub"]).nullable().optional(),title:z.string().trim().min(1).max(240),coverImage:z.string().url().max(2000).nullable().optional(),genres:z.array(z.string().trim().max(40)).max(30).optional(),malId:z.number().int().positive().nullable().optional(),totalEpisodes:z.number().int().positive().max(10000).nullable().optional(),completed:z.boolean().optional()});
const user=(r:AuthenticatedRequest)=>{if(!r.authUser)throw new AppError(401,"AUTH_REQUIRED","Authentication is required.");return r.authUser.id;};
const action=(fn:(r:AuthenticatedRequest)=>Promise<unknown>,created=false)=>async(r:AuthenticatedRequest,res:Response,next:NextFunction)=>{try{res.status(created?201:200).json({success:true,data:await fn(r)});}catch(error){next(error);}};

export function createUserPlaybackRouter(repository:UserPlaybackRepository){const router=Router();
router.get("/progress/continue-watching",action(r=>repository.continueWatching(user(r),pageLimit.parse(r.query.limit??20))));router.get("/progress/recently-completed",action(r=>repository.recentlyCompleted(user(r),pageLimit.parse(r.query.limit??20))));router.get("/progress/:animeId",action(r=>repository.animeProgress(user(r),id.parse(r.params.animeId))));router.get("/progress/:animeId/:episode",action(r=>repository.episodeProgress(user(r),id.parse(r.params.animeId),episode.parse(r.params.episode))));
router.put("/progress/:animeId/:episode",action(async r=>{const input=body.parse(r.body),anilistId=id.parse(r.params.animeId),episodeNumber=episode.parse(r.params.episode);if(input.currentTime>input.duration+5)throw new AppError(400,"INVALID_PROGRESS","Playback progress is invalid.");const completed=Boolean(input.completed||input.currentTime/input.duration*100>=92);const normalized={...input,anilistId,episodeNumber,completed};const saved=await repository.saveProgress(user(r),normalized);if(input.currentTime>=30||input.currentTime/input.duration*100>=5||completed)await repository.saveHistory(user(r),normalized);return saved;}));
router.delete("/progress/:animeId/:episode",action(async r=>({removed:await repository.removeEpisodeProgress(user(r),id.parse(r.params.animeId),episode.parse(r.params.episode))})));router.delete("/progress/:animeId",action(async r=>({removed:await repository.removeAnimeProgress(user(r),id.parse(r.params.animeId))})));
router.get("/watch-history",action(r=>repository.history(user(r),pageLimit.parse(r.query.limit??100))));router.delete("/watch-history/:id",action(async r=>({removed:await repository.removeHistory(user(r),id.parse(r.params.id))})));router.delete("/watch-history",action(async r=>({removed:await repository.clearHistory(user(r))})));router.post("/watch-history",action(r=>{const input=body.parse(r.body);return repository.saveHistory(user(r),{...input,anilistId:id.parse(r.body.anilistId),episodeNumber:episode.parse(r.body.episodeNumber),completed:Boolean(input.completed)});},true));return router;}
