import { createContext, useCallback, useContext, useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import {libraryQueryApi,type Membership} from '../services/libraryQueryApi';
import { libraryApi } from "../services/libraryApi";
import type { Anime } from "../types/anime";
import { useAuth } from "../auth/AuthContext";
import { toLibraryAnime, type Favorite, type RecentlyViewed, type SearchHistoryItem, type WatchlistItem, type WatchlistStatus } from "../types/library";

type LibraryContextValue = {
  membership: Membership; revisions: Record<string,number>; refreshFavorites: () => Promise<void>; refreshWatchlist: () => Promise<void>; refreshHistory: () => Promise<void>; favorites: Favorite[]; watchlist: WatchlistItem[]; history: RecentlyViewed[]; searchHistory: SearchHistoryItem[]; settings: Record<string, string>; loading: boolean; error: string | null; notice: string | null;
  isFavorite: (id: number) => boolean; favorite: (anime: Anime) => Promise<void>; removeFavorite: (id: number) => Promise<void>;
  addToWatchlist: (anime: Anime, status: WatchlistStatus) => Promise<void>; updateWatchlist: (id: number, status: WatchlistStatus) => Promise<void>; removeFromWatchlist: (id: number) => Promise<void>; getWatchlistItem: (id: number) => Pick<WatchlistItem,"anilistId"|"status"> | undefined;
  recordViewed: (anime: Anime) => Promise<void>; removeHistory: (id: number) => Promise<void>; clearHistory: () => Promise<void>; addSearch: (query: string) => Promise<void>; removeSearch: (id: number) => Promise<void>; clearSearches: () => Promise<void>; updateSetting: (key: string, value: string) => Promise<void>; refresh: () => Promise<void>;
};
const LibraryContext = createContext<LibraryContextValue | null>(null);

export function LibraryProvider({ children }: { children: ReactNode }) {
  const auth = useAuth();
  const [membership,setMembership]=useState<Membership>({favoriteIds:[],watchlist:[],recentlyViewedCount:0});
  const [revisions,setRevisions]=useState<Record<string,number>>({});
  const pending=useRef(new Set<string>());
  const settingQueue=useRef(new Map<string,Promise<void>>());
  const settingVersion=useRef(new Map<string,number>());
  const bump=useCallback((collection:string)=>setRevisions(v=>({...v,[collection]:(v[collection]??0)+1})),[]);
  const refreshMembership=useCallback(async()=>{try{setMembership(await libraryQueryApi.membership());}catch{setError("Unable to refresh library membership. Please retry.");}},[]);
  const refreshFavorites=useCallback(async()=>{setFavorites(await libraryApi.favorites.all());await refreshMembership();bump("favorites");},[refreshMembership,bump]);
  const refreshWatchlist=useCallback(async()=>{setWatchlist(await libraryApi.watchlist.all());await refreshMembership();bump("watchlist");},[refreshMembership,bump]);
  const refreshHistory=useCallback(async()=>{setHistory(await libraryApi.history.all());await refreshMembership();bump("recently-viewed");},[refreshMembership,bump]);
  const [favorites, setFavorites] = useState<Favorite[]>([]); const [watchlist, setWatchlist] = useState<WatchlistItem[]>([]); const [history, setHistory] = useState<RecentlyViewed[]>([]); const [searchHistory, setSearchHistory] = useState<SearchHistoryItem[]>([]); const [settings, setSettings] = useState<Record<string, string>>({}); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null); const noticeTimer = useRef<number | undefined>(undefined);
  const notify = useCallback((message: string) => { setNotice(message); window.clearTimeout(noticeTimer.current); noticeTimer.current = window.setTimeout(() => setNotice(null), 2800); }, []);
  const refresh = useCallback(async () => { if(auth.mode==="supabase"&&!auth.user){setMembership({favoriteIds:[],watchlist:[],recentlyViewedCount:0});setFavorites([]);setWatchlist([]);setHistory([]);setSearchHistory([]);setSettings({});setError(null);setLoading(false);return;}setLoading(true); setError(null); try { const [m,s,p] = await Promise.all([libraryQueryApi.membership(),libraryApi.searchHistory.all(),libraryApi.settings.all()]);setFavorites([]);setWatchlist([]);setHistory([]);setMembership(m);setRevisions(v=>Object.fromEntries(['favorites','watchlist','recently-viewed','watch-history','continue-watching','recently-completed'].map(k=>[k,(v[k]??0)+1])));setSearchHistory(s);setSettings(p); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load private AniVerse data."); } finally { setLoading(false); } }, [auth.mode,auth.user]);
  useEffect(() => { void refresh(); return () => window.clearTimeout(noticeTimer.current); }, [refresh]);
  const favorite = useCallback(async (anime: Anime) => { const operation="favorites:"+anime.id;if(pending.current.has(operation))return;pending.current.add(operation);const wasFavorite=membership.favoriteIds.includes(anime.id);setMembership(m=>({...m,favoriteIds:[...m.favoriteIds.filter(x=>x!==anime.id),anime.id]})); const snapshot = toLibraryAnime(anime); const previous = favorites; setFavorites((items) => [...items.filter((item) => item.anilistId !== anime.id), { ...snapshot, id: -anime.id, addedAt: new Date().toISOString() }]); try { const saved = await libraryApi.favorites.add(snapshot); setFavorites((items) => [...items.filter((item) => item.anilistId !== anime.id), saved]); setMembership(m=>({...m,favoriteIds:[...m.favoriteIds.filter(id=>id!==anime.id),anime.id]}));bump('favorites'); notify("Added to Favorites"); } catch (reason) {setMembership(m=>({...m,favoriteIds:[...m.favoriteIds.filter(x=>x!==anime.id),...(wasFavorite?[anime.id]:[])]})); setFavorites(items=>[...items.filter(x=>x.anilistId!==anime.id),...previous.filter(x=>x.anilistId===anime.id)]); notify(reason instanceof Error ? reason.message : "Unable to update favorites."); } finally {pending.current.delete(operation);} }, [favorites, notify,membership,refreshMembership,bump]);
  const removeFavorite = useCallback(async (id: number) => { const operation="favorites:"+id;if(pending.current.has(operation))return;pending.current.add(operation);const wasFavorite=membership.favoriteIds.includes(id);setMembership(m=>({...m,favoriteIds:m.favoriteIds.filter(x=>x!==id)})); const previous = favorites; setFavorites((items) => items.filter((item) => item.anilistId !== id)); try { await libraryApi.favorites.remove(id); setMembership(m=>({...m,favoriteIds:m.favoriteIds.filter(value=>value!==id)}));bump('favorites'); notify("Removed from Favorites"); } catch (reason) {setMembership(m=>({...m,favoriteIds:[...m.favoriteIds.filter(x=>x!==id),...(wasFavorite?[id]:[])]})); setFavorites(items=>[...items.filter(x=>x.anilistId!==id),...previous.filter(x=>x.anilistId===id)]); notify(reason instanceof Error ? reason.message : "Unable to update favorites."); } finally {pending.current.delete(operation);} }, [favorites, notify,membership,refreshMembership,bump]);
  const addToWatchlist = useCallback(async (anime: Anime, status: WatchlistStatus) => { const operation="watchlist:"+anime.id;if(pending.current.has(operation))return;pending.current.add(operation);const oldStatus=membership.watchlist.find(x=>x.anilistId===anime.id);setMembership(m=>({...m,watchlist:[...m.watchlist.filter(x=>x.anilistId!==anime.id),{anilistId:anime.id,status}]})); const snapshot = toLibraryAnime(anime); const previous = watchlist; setWatchlist((items) => [...items.filter((item) => item.anilistId !== anime.id), { ...snapshot, id: -anime.id, status, notes: null, addedAt: new Date().toISOString(), updatedAt: new Date().toISOString() }]); try { const saved = await libraryApi.watchlist.add(snapshot, status); setWatchlist((items) => [...items.filter((item) => item.anilistId !== anime.id), saved]); setMembership(m=>({...m,watchlist:[...m.watchlist.filter(x=>x.anilistId!==saved.anilistId),{anilistId:saved.anilistId,status:saved.status}]}));bump('watchlist'); notify("My List updated"); } catch (reason) {setMembership(m=>({...m,watchlist:[...m.watchlist.filter(x=>x.anilistId!==anime.id),...(oldStatus?[oldStatus]:[])]})); setWatchlist(items=>[...items.filter(x=>x.anilistId!==anime.id),...previous.filter(x=>x.anilistId===anime.id)]); notify(reason instanceof Error ? reason.message : "Unable to update My List."); } finally {pending.current.delete(operation);} }, [notify, watchlist,membership,refreshMembership,bump]);
  const updateWatchlist = useCallback(async (id: number, status: WatchlistStatus) => { const operation="watchlist:"+id;if(pending.current.has(operation))return;pending.current.add(operation);const oldStatus=membership.watchlist.find(x=>x.anilistId===id);setMembership(m=>({...m,watchlist:[...m.watchlist.filter(x=>x.anilistId!==id),{anilistId:id,status}]})); const previous = watchlist; setWatchlist((items) => items.map((item) => item.anilistId === id ? { ...item, status, updatedAt: new Date().toISOString() } : item)); try { const saved = await libraryApi.watchlist.update(id, status); setWatchlist((items) => items.map((item) => item.anilistId === id ? saved : item)); setMembership(m=>({...m,watchlist:[...m.watchlist.filter(x=>x.anilistId!==saved.anilistId),{anilistId:saved.anilistId,status:saved.status}]}));bump('watchlist'); notify("My List updated"); } catch (reason) {setMembership(m=>({...m,watchlist:[...m.watchlist.filter(x=>x.anilistId!==id),...(oldStatus?[oldStatus]:[])]})); setWatchlist(items=>[...items.filter(x=>x.anilistId!==id),...previous.filter(x=>x.anilistId===id)]); notify(reason instanceof Error ? reason.message : "Unable to update My List."); } finally {pending.current.delete(operation);} }, [notify, watchlist,membership,refreshMembership,bump]);
  const removeFromWatchlist = useCallback(async (id: number) => { const operation="watchlist:"+id;if(pending.current.has(operation))return;pending.current.add(operation);const oldStatus=membership.watchlist.find(x=>x.anilistId===id);setMembership(m=>({...m,watchlist:m.watchlist.filter(x=>x.anilistId!==id)})); const previous = watchlist; setWatchlist((items) => items.filter((item) => item.anilistId !== id)); try { await libraryApi.watchlist.remove(id); setMembership(m=>({...m,watchlist:m.watchlist.filter(x=>x.anilistId!==id)}));bump('watchlist'); notify("Removed from My List"); } catch (reason) {setMembership(m=>({...m,watchlist:[...m.watchlist.filter(x=>x.anilistId!==id),...(oldStatus?[oldStatus]:[])]})); setWatchlist(items=>[...items.filter(x=>x.anilistId!==id),...previous.filter(x=>x.anilistId===id)]); notify(reason instanceof Error ? reason.message : "Unable to update My List."); } finally {pending.current.delete(operation);} }, [notify, watchlist,membership,refreshMembership,bump]);
  const recordViewed = useCallback(async (anime: Anime) => { try { const saved = await libraryApi.history.record(toLibraryAnime(anime)); setHistory((items) => [saved, ...items.filter((item) => item.anilistId !== anime.id)]);if(saved.viewCount===1)setMembership(m=>({...m,recentlyViewedCount:Math.min(250,m.recentlyViewedCount+1)}));bump("recently-viewed"); } catch { /* viewing should never block details */ } }, [bump]);
  const removeHistory = useCallback(async (id: number) => { const operation="recently-viewed:"+id;if(pending.current.has(operation))return;pending.current.add(operation); const previous = history; setHistory((items) => items.filter((item) => item.anilistId !== id)); try { await libraryApi.history.remove(id); setMembership(m=>({...m,recentlyViewedCount:Math.max(0,m.recentlyViewedCount-1)}));bump('recently-viewed'); notify("Removed from Recently Viewed"); } catch { setHistory(items=>[...items.filter(x=>x.anilistId!==id),...previous.filter(x=>x.anilistId===id)]); notify("Unable to update history."); } finally {pending.current.delete(operation);} }, [history, notify,refreshMembership,bump]);
  const clearHistory = useCallback(async () => { const previous = history; setHistory([]); try { await libraryApi.history.clear(); setMembership(m=>({...m,recentlyViewedCount:0}));bump('recently-viewed'); notify("History cleared"); } catch { setHistory(items=>[...items,...previous.filter(p=>!items.some(x=>x.anilistId===p.anilistId))]); notify("Unable to clear history."); } }, [history, notify,refreshMembership,bump]);
  const addSearch = useCallback(async (query: string) => { try { const saved = await libraryApi.searchHistory.add(query); setSearchHistory((items) => [saved, ...items.filter((item) => item.id !== saved.id && item.query.toLowerCase() !== saved.query.toLowerCase())]); } catch { /* optional enhancement */ } }, []);
  const removeSearch = useCallback(async (id: number) => { const previous=searchHistory.find(x=>x.id===id);setSearchHistory((items) => items.filter((item) => item.id !== id)); try { await libraryApi.searchHistory.remove(id); } catch { if(previous)setSearchHistory(items=>[...items.filter(x=>x.id!==id),previous]); } }, [searchHistory]);
  const clearSearches = useCallback(async () => { const previous = searchHistory; setSearchHistory([]); try { await libraryApi.searchHistory.clear(); notify("Search history cleared"); } catch { setSearchHistory(previous); notify("Unable to clear search history."); } }, [notify, searchHistory]);
  const updateSetting = useCallback(async (key: string, value: string) => {
    const previous = settings[key]; const version=(settingVersion.current.get(key)??0)+1;settingVersion.current.set(key,version);
    setSettings(items=>({...items,[key]:value}));
    const task=(settingQueue.current.get(key)??Promise.resolve()).then(async()=>{try{await libraryApi.settings.update(key,value);if(settingVersion.current.get(key)===version)notify("Settings saved");}catch{if(settingVersion.current.get(key)===version){setSettings(items=>({...items,[key]:previous}));notify("Unable to save settings.");}}});
    settingQueue.current.set(key,task);await task;if(settingQueue.current.get(key)===task)settingQueue.current.delete(key);
  },[notify,settings]);
  const value = useMemo<LibraryContextValue>(() => ({ membership,revisions,refreshFavorites,refreshWatchlist,refreshHistory,favorites, watchlist, history, searchHistory, settings, loading, error, notice, isFavorite: (id) => membership.favoriteIds.includes(id), favorite, removeFavorite, addToWatchlist, updateWatchlist, removeFromWatchlist, getWatchlistItem: (id) => membership.watchlist.find(item=>item.anilistId===id), recordViewed, removeHistory, clearHistory, addSearch, removeSearch, clearSearches, updateSetting, refresh }), [membership,revisions,refreshFavorites,refreshWatchlist,refreshHistory,favorites, watchlist, history, searchHistory, settings, loading, error, notice, favorite, removeFavorite, addToWatchlist, updateWatchlist, removeFromWatchlist, recordViewed, removeHistory, clearHistory, addSearch, removeSearch, clearSearches, updateSetting, refresh]);
  return <LibraryContext.Provider value={value}>{children}{notice && <div role="status" className="fixed bottom-20 left-1/2 z-[60] -translate-x-1/2 rounded-md border border-outline bg-surface px-4 py-3 text-sm font-semibold text-foreground shadow-2xl md:bottom-6">{notice}</div>}</LibraryContext.Provider>;
}

export function useLibrary() { const context = useContext(LibraryContext); if (!context) throw new Error("useLibrary must be used within LibraryProvider"); return context; }
export function useOptionalLibrary() { return useContext(LibraryContext); }
