import { createContext, useCallback, useContext, useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { libraryApi } from "../services/libraryApi";
import type { Anime } from "../types/anime";
import { useAuth } from "../auth/AuthContext";
import { toLibraryAnime, type Favorite, type RecentlyViewed, type SearchHistoryItem, type WatchlistItem, type WatchlistStatus } from "../types/library";

type LibraryContextValue = {
  favorites: Favorite[]; watchlist: WatchlistItem[]; history: RecentlyViewed[]; searchHistory: SearchHistoryItem[]; settings: Record<string, string>; loading: boolean; error: string | null; notice: string | null;
  isFavorite: (id: number) => boolean; favorite: (anime: Anime) => Promise<void>; removeFavorite: (id: number) => Promise<void>;
  addToWatchlist: (anime: Anime, status: WatchlistStatus) => Promise<void>; updateWatchlist: (id: number, status: WatchlistStatus) => Promise<void>; removeFromWatchlist: (id: number) => Promise<void>; getWatchlistItem: (id: number) => WatchlistItem | undefined;
  recordViewed: (anime: Anime) => Promise<void>; removeHistory: (id: number) => Promise<void>; clearHistory: () => Promise<void>; addSearch: (query: string) => Promise<void>; removeSearch: (id: number) => Promise<void>; clearSearches: () => Promise<void>; updateSetting: (key: string, value: string) => Promise<void>; refresh: () => Promise<void>;
};
const LibraryContext = createContext<LibraryContextValue | null>(null);

export function LibraryProvider({ children }: { children: ReactNode }) {
  const auth = useAuth();
  const [favorites, setFavorites] = useState<Favorite[]>([]); const [watchlist, setWatchlist] = useState<WatchlistItem[]>([]); const [history, setHistory] = useState<RecentlyViewed[]>([]); const [searchHistory, setSearchHistory] = useState<SearchHistoryItem[]>([]); const [settings, setSettings] = useState<Record<string, string>>({}); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null); const noticeTimer = useRef<number | undefined>(undefined);
  const notify = useCallback((message: string) => { setNotice(message); window.clearTimeout(noticeTimer.current); noticeTimer.current = window.setTimeout(() => setNotice(null), 2800); }, []);
  const refresh = useCallback(async () => { if(auth.mode==="supabase"&&!auth.user){setFavorites([]);setWatchlist([]);setHistory([]);setSearchHistory([]);setSettings({});setError(null);setLoading(false);return;}setLoading(true); setError(null); try { const [f, w, h, s, p] = await Promise.all([libraryApi.favorites.all(), libraryApi.watchlist.all(), libraryApi.history.all(), libraryApi.searchHistory.all(), libraryApi.settings.all()]); setFavorites(f); setWatchlist(w); setHistory(h); setSearchHistory(s); setSettings(p); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load private AniVerse data."); } finally { setLoading(false); } }, [auth.mode,auth.user]);
  useEffect(() => { void refresh(); return () => window.clearTimeout(noticeTimer.current); }, [refresh]);
  const favorite = useCallback(async (anime: Anime) => { const snapshot = toLibraryAnime(anime); const previous = favorites; setFavorites((items) => [...items.filter((item) => item.anilistId !== anime.id), { ...snapshot, id: -anime.id, addedAt: new Date().toISOString() }]); try { const saved = await libraryApi.favorites.add(snapshot); setFavorites((items) => [...items.filter((item) => item.anilistId !== anime.id), saved]); notify("Added to Favorites"); } catch (reason) { setFavorites(previous); notify(reason instanceof Error ? reason.message : "Unable to update favorites."); } }, [favorites, notify]);
  const removeFavorite = useCallback(async (id: number) => { const previous = favorites; setFavorites((items) => items.filter((item) => item.anilistId !== id)); try { await libraryApi.favorites.remove(id); notify("Removed from Favorites"); } catch (reason) { setFavorites(previous); notify(reason instanceof Error ? reason.message : "Unable to update favorites."); } }, [favorites, notify]);
  const addToWatchlist = useCallback(async (anime: Anime, status: WatchlistStatus) => { const snapshot = toLibraryAnime(anime); const previous = watchlist; setWatchlist((items) => [...items.filter((item) => item.anilistId !== anime.id), { ...snapshot, id: -anime.id, status, notes: null, addedAt: new Date().toISOString(), updatedAt: new Date().toISOString() }]); try { const saved = await libraryApi.watchlist.add(snapshot, status); setWatchlist((items) => [...items.filter((item) => item.anilistId !== anime.id), saved]); notify("My List updated"); } catch (reason) { setWatchlist(previous); notify(reason instanceof Error ? reason.message : "Unable to update My List."); } }, [notify, watchlist]);
  const updateWatchlist = useCallback(async (id: number, status: WatchlistStatus) => { const previous = watchlist; setWatchlist((items) => items.map((item) => item.anilistId === id ? { ...item, status, updatedAt: new Date().toISOString() } : item)); try { const saved = await libraryApi.watchlist.update(id, status); setWatchlist((items) => items.map((item) => item.anilistId === id ? saved : item)); notify("My List updated"); } catch (reason) { setWatchlist(previous); notify(reason instanceof Error ? reason.message : "Unable to update My List."); } }, [notify, watchlist]);
  const removeFromWatchlist = useCallback(async (id: number) => { const previous = watchlist; setWatchlist((items) => items.filter((item) => item.anilistId !== id)); try { await libraryApi.watchlist.remove(id); notify("Removed from My List"); } catch (reason) { setWatchlist(previous); notify(reason instanceof Error ? reason.message : "Unable to update My List."); } }, [notify, watchlist]);
  const recordViewed = useCallback(async (anime: Anime) => { try { const saved = await libraryApi.history.record(toLibraryAnime(anime)); setHistory((items) => [saved, ...items.filter((item) => item.anilistId !== anime.id)]); } catch { /* viewing should never block details */ } }, []);
  const removeHistory = useCallback(async (id: number) => { const previous = history; setHistory((items) => items.filter((item) => item.anilistId !== id)); try { await libraryApi.history.remove(id); notify("Removed from Recently Viewed"); } catch { setHistory(previous); notify("Unable to update history."); } }, [history, notify]);
  const clearHistory = useCallback(async () => { const previous = history; setHistory([]); try { await libraryApi.history.clear(); notify("History cleared"); } catch { setHistory(previous); notify("Unable to clear history."); } }, [history, notify]);
  const addSearch = useCallback(async (query: string) => { try { const saved = await libraryApi.searchHistory.add(query); setSearchHistory((items) => [saved, ...items.filter((item) => item.id !== saved.id && item.query.toLowerCase() !== saved.query.toLowerCase())]); } catch { /* optional enhancement */ } }, []);
  const removeSearch = useCallback(async (id: number) => { setSearchHistory((items) => items.filter((item) => item.id !== id)); try { await libraryApi.searchHistory.remove(id); } catch { void refresh(); } }, [refresh]);
  const clearSearches = useCallback(async () => { const previous = searchHistory; setSearchHistory([]); try { await libraryApi.searchHistory.clear(); notify("Search history cleared"); } catch { setSearchHistory(previous); notify("Unable to clear search history."); } }, [notify, searchHistory]);
  const updateSetting = useCallback(async (key: string, value: string) => { const previous = settings[key]; setSettings((items) => ({ ...items, [key]: value })); try { await libraryApi.settings.update(key, value); notify("Settings saved"); } catch { setSettings((items) => ({ ...items, [key]: previous })); notify("Unable to save settings."); } }, [notify, settings]);
  const value = useMemo<LibraryContextValue>(() => ({ favorites, watchlist, history, searchHistory, settings, loading, error, notice, isFavorite: (id) => favorites.some((item) => item.anilistId === id), favorite, removeFavorite, addToWatchlist, updateWatchlist, removeFromWatchlist, getWatchlistItem: (id) => watchlist.find((item) => item.anilistId === id), recordViewed, removeHistory, clearHistory, addSearch, removeSearch, clearSearches, updateSetting, refresh }), [favorites, watchlist, history, searchHistory, settings, loading, error, notice, favorite, removeFavorite, addToWatchlist, updateWatchlist, removeFromWatchlist, recordViewed, removeHistory, clearHistory, addSearch, removeSearch, clearSearches, updateSetting, refresh]);
  return <LibraryContext.Provider value={value}>{children}{notice && <div role="status" className="fixed bottom-20 left-1/2 z-[60] -translate-x-1/2 rounded-md border border-outline bg-surface px-4 py-3 text-sm font-semibold text-foreground shadow-2xl md:bottom-6">{notice}</div>}</LibraryContext.Provider>;
}

export function useLibrary() { const context = useContext(LibraryContext); if (!context) throw new Error("useLibrary must be used within LibraryProvider"); return context; }
export function useOptionalLibrary() { return useContext(LibraryContext); }
