import {render,screen,waitFor} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {beforeEach,describe,expect,it,vi} from 'vitest';
import {LibraryProvider,useLibrary} from './LibraryContext';
import {libraryApi} from '../services/libraryApi';
import {libraryQueryApi} from '../services/libraryQueryApi';
import {libraryToAnime,type LibraryAnime} from '../types/library';
vi.mock('../auth/AuthContext',()=>({useAuth:()=>({mode:'local',user:null})}));
vi.mock('../services/libraryQueryApi',()=>({libraryQueryApi:{membership:vi.fn()}}));
vi.mock('../services/libraryApi',()=>({libraryApi:{favorites:{all:vi.fn(),add:vi.fn(),remove:vi.fn()},watchlist:{all:vi.fn(),add:vi.fn(),update:vi.fn(),remove:vi.fn()},history:{all:vi.fn()},searchHistory:{all:vi.fn()},settings:{all:vi.fn(),update:vi.fn()}}}));
const item=(id:number):LibraryAnime=>({anilistId:id,title:`Anime ${id}`,titleRomaji:null,coverImage:null,bannerImage:null,format:null,seasonYear:null,averageScore:null,genres:[],malId:null});
function Probe(){const l=useLibrary();return <><p>{l.loading?'Loading':'Ready'}</p><p>Favorites: {l.favorites.map(x=>x.anilistId).join(',')}</p><p>View: {l.settings.library_view_mode}</p><button onClick={()=>void l.favorite(libraryToAnime(item(1)))}>Add one</button><button onClick={()=>void l.favorite(libraryToAnime(item(2)))}>Add two</button><button onClick={()=>void l.refreshFavorites()}>Refresh favorites</button><button onClick={()=>void l.updateSetting('library_view_mode','list')}>List view</button><button onClick={()=>void l.updateSetting('library_view_mode','grid')}>Grid view</button></>;}
describe('Stage 10.2 focused library state',()=>{
 beforeEach(()=>{vi.clearAllMocks();vi.mocked(libraryQueryApi.membership).mockResolvedValue({favoriteIds:[],watchlist:[],recentlyViewedCount:0});vi.mocked(libraryApi.searchHistory.all).mockResolvedValue([]);vi.mocked(libraryApi.settings.all).mockResolvedValue({});vi.mocked(libraryApi.favorites.all).mockResolvedValue([]);});
 it('initializes compact membership without downloading unrelated full collections',async()=>{render(<LibraryProvider><Probe /></LibraryProvider>);await screen.findByText('Ready');expect(libraryApi.favorites.all).not.toHaveBeenCalled();expect(libraryApi.watchlist.all).not.toHaveBeenCalled();expect(libraryApi.history.all).not.toHaveBeenCalled();expect(libraryQueryApi.membership).toHaveBeenCalledTimes(1);});
 it('refreshes favorites without reloading watchlist or history',async()=>{render(<LibraryProvider><Probe /></LibraryProvider>);await screen.findByText('Ready');await userEvent.click(screen.getByText('Refresh favorites'));await waitFor(()=>expect(libraryApi.favorites.all).toHaveBeenCalledTimes(1));expect(libraryApi.watchlist.all).not.toHaveBeenCalled();expect(libraryApi.history.all).not.toHaveBeenCalled();});
 it('rolls back one failed addition while preserving a concurrent successful item',async()=>{let reject!:(reason:Error)=>void;vi.mocked(libraryApi.favorites.add).mockImplementation(anime=>anime.anilistId===1?new Promise((_r,j)=>{reject=j;}):Promise.resolve({...item(2),id:2,addedAt:new Date().toISOString()}));render(<LibraryProvider><Probe /></LibraryProvider>);await screen.findByText('Ready');await userEvent.click(screen.getByText('Add one'));await userEvent.click(screen.getByText('Add two'));await waitFor(()=>expect(screen.getByText('Favorites: 1,2')).toBeInTheDocument());reject(new Error('Unable to save.'));await waitFor(()=>expect(screen.getByText('Favorites: 2')).toBeInTheDocument());expect(libraryApi.watchlist.all).not.toHaveBeenCalled();expect(libraryQueryApi.membership).toHaveBeenCalledTimes(1);});
 it('prevents duplicate requests for the same pending record',async()=>{vi.mocked(libraryApi.favorites.add).mockImplementation(()=>new Promise(()=>{}));render(<LibraryProvider><Probe /></LibraryProvider>);await screen.findByText('Ready');await userEvent.click(screen.getByText('Add one'));await userEvent.click(screen.getByText('Add one'));expect(libraryApi.favorites.add).toHaveBeenCalledTimes(1);});
 it('orders preference requests while keeping the latest optimistic selection',async()=>{let finish!:(value:{key:string;value:string})=>void;vi.mocked(libraryApi.settings.update).mockImplementationOnce(()=>new Promise(r=>{finish=r;})).mockResolvedValue({key:'library_view_mode',value:'grid'});render(<LibraryProvider><Probe /></LibraryProvider>);await screen.findByText('Ready');await userEvent.click(screen.getByText('List view'));await userEvent.click(screen.getByText('Grid view'));expect(libraryApi.settings.update).toHaveBeenCalledTimes(1);expect(screen.getByText('View: grid')).toBeInTheDocument();finish({key:'library_view_mode',value:'list'});await waitFor(()=>expect(libraryApi.settings.update).toHaveBeenCalledTimes(2));expect(vi.mocked(libraryApi.settings.update).mock.calls.map(x=>x[1])).toEqual(['list','grid']);expect(screen.getByText('View: grid')).toBeInTheDocument();});
});
