import {expect,test} from '@playwright/test';
import {randomUUID} from 'node:crypto';
test('local library search paging view persistence status filters and history sections',async({page,request})=>{
 const prefix='Library checkpoint '+randomUUID().slice(0,8);const ids=Array.from({length:14},(_,i)=>810000+i);const settings=(await (await request.get('/api/settings')).json()).data;
 await page.emulateMedia({reducedMotion:'reduce'});
 try{
  for(const [i,id]of ids.entries()){const anime={anilistId:id,title:`${prefix} ${String(i+1).padStart(2,'0')}`,genres:i%2?['Drama']:['Action'],format:'TV',seasonYear:2020+i,averageScore:70+i};expect((await request.post('/api/favorites',{data:anime})).status()).toBe(201);expect((await request.post('/api/watchlist',{data:{anime,status:i%2?'PLANNING':'WATCHING'}})).status()).toBe(201);}
  await request.patch('/api/settings/library_page_size',{data:{value:'12'}});await request.patch('/api/settings/library_view_mode',{data:{value:'grid'}});
  const reads:string[]=[];page.on('request',r=>{const p=new URL(r.url()).pathname;if(r.method()==='GET'&&['/api/favorites','/api/watchlist','/api/history','/api/library/favorites','/api/library-membership','/api/settings','/api/search-history'].includes(p))reads.push(p);});
  const start=Date.now();await page.goto('/favorites');await expect(page.getByText(/\d+ results/, {exact:true})).toBeVisible();
  expect(reads.filter(p=>p==='/api/library/favorites')).toHaveLength(1);expect(reads).not.toContain('/api/favorites');expect(reads).not.toContain('/api/watchlist');expect(reads).not.toContain('/api/history');
  await test.info().attach('library-initial-reads',{body:JSON.stringify({requests:reads.length,pageRequests:1,renderReadyMs:Date.now()-start}),contentType:'application/json'});
  await page.getByRole('searchbox').fill(prefix);await expect(page.getByText('14 results',{exact:true})).toBeVisible();await expect(page.getByText('Page 1 of 2')).toBeVisible();await page.getByRole('button',{name:'Next',exact:true}).click();await expect(page.getByText('Page 2 of 2')).toBeVisible();
  await page.getByRole('button',{name:'list',exact:true}).focus();await page.keyboard.press('Enter');await expect(page.getByRole('button',{name:'list',exact:true})).toHaveAttribute('aria-pressed','true');await page.reload();await expect(page.getByRole('button',{name:'list',exact:true})).toHaveAttribute('aria-pressed','true');await expect(page.getByText('14 results',{exact:true})).toBeVisible();
  await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Filters',exact:true}).click();const drawer=page.getByRole('dialog',{name:'Library filters'});await expect(drawer).toBeVisible();await drawer.getByLabel('Genre', {exact:true}).selectOption('Action');await drawer.getByLabel('Sort', {exact:true}).selectOption('title:desc');await drawer.getByRole('button',{name:'Apply filters'}).click();await expect(page.getByText('7 results',{exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.goto('/my-list?search='+encodeURIComponent(prefix));await expect(page.getByText('14 results',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Filters',exact:true}).click();await page.getByRole('dialog').getByLabel('Status',{exact:true}).selectOption('WATCHING');await page.getByRole('dialog').getByRole('button',{name:'Apply filters'}).click();await expect(page.getByText('7 results',{exact:true})).toBeVisible();
  await page.getByLabel(`Status for ${prefix} 01`).selectOption('COMPLETED');await expect(page.getByText('6 results',{exact:true})).toBeVisible();await page.reload();await expect(page.getByText('6 results',{exact:true})).toBeVisible();
  await page.goto('/history');await expect(page.getByRole('heading',{name:'Watch History',exact:true})).toBeVisible();await page.getByRole('button',{name:'Recently Viewed',exact:true}).click();await expect(page.getByRole('heading',{name:'Recently Viewed',exact:true})).toBeVisible();await page.getByRole('button',{name:'Continue Watching',exact:true}).click();await expect(page.getByRole('heading',{name:'Continue Watching',exact:true})).toBeVisible();
 }finally{for(const id of ids){await request.delete(`/api/favorites/${id}`);await request.delete(`/api/watchlist/${id}`);}await request.patch('/api/settings/library_view_mode',{data:{value:settings.library_view_mode??'grid'}});await request.patch('/api/settings/library_page_size',{data:{value:settings.library_page_size??'24'}});}
});
