-- AniVerse Phase 9 PostgreSQL/Supabase schema. Apply before application startup.
create table if not exists public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  anilist_id integer not null check (anilist_id > 0), mal_id integer,
  title varchar(240) not null, title_romaji varchar(240), cover_image varchar(2000), banner_image varchar(2000),
  format varchar(30), season_year integer, average_score numeric(5,2), genres jsonb not null default '[]'::jsonb,
  added_at timestamptz not null default now(), unique(user_id, anilist_id)
);
create table if not exists public.watchlist (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  anilist_id integer not null check (anilist_id > 0), mal_id integer,
  title varchar(240) not null, title_romaji varchar(240), cover_image varchar(2000), banner_image varchar(2000),
  format varchar(30), season_year integer, average_score numeric(5,2), genres jsonb not null default '[]'::jsonb,
  status varchar(20) not null check(status in ('PLANNING','WATCHING','COMPLETED','ON_HOLD','DROPPED')),
  notes varchar(2000), added_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  unique(user_id, anilist_id)
);
create table if not exists public.app_settings (
  user_id uuid not null references auth.users(id) on delete cascade,
  key varchar(50) not null, value varchar(100) not null, updated_at timestamptz not null default now(),
  primary key(user_id, key)
);
create table if not exists public.search_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  query varchar(100) not null, normalized_query varchar(100) not null,
  searched_at timestamptz not null default now(), unique(user_id, normalized_query)
);
create table if not exists public.recently_viewed (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  anilist_id integer not null check(anilist_id > 0), mal_id integer, title varchar(240) not null,
  title_romaji varchar(240), cover_image varchar(2000), banner_image varchar(2000), format varchar(30),
  season_year integer, average_score numeric(5,2), genres jsonb not null default '[]'::jsonb,
  last_viewed_at timestamptz not null default now(), view_count integer not null default 1,
  unique(user_id, anilist_id)
);
create table if not exists public.episode_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  anilist_id integer not null check(anilist_id > 0), mal_id integer, episode_number integer not null check(episode_number > 0),
  total_episodes integer, title varchar(240) not null, cover_image varchar(2000), genres jsonb not null default '[]'::jsonb,
  current_time_seconds double precision not null default 0, duration double precision not null check(duration > 0),
  percentage double precision not null check(percentage between 0 and 100), completed boolean not null default false,
  provider_id varchar(30), language varchar(10), first_watched_at timestamptz not null default now(),
  last_watched_at timestamptz not null default now(), completed_at timestamptz, created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(), unique(user_id, anilist_id, episode_number)
);
create table if not exists public.watch_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  anilist_id integer not null check(anilist_id > 0), mal_id integer, episode_number integer not null check(episode_number > 0),
  total_episodes integer, title varchar(240) not null, cover_image varchar(2000), genres jsonb not null default '[]'::jsonb,
  progress_percentage double precision not null check(progress_percentage between 0 and 100), completed boolean not null default false,
  provider_id varchar(30), language varchar(10), watched_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(), unique(user_id, anilist_id, episode_number)
);

create index if not exists idx_favorites_user_added on public.favorites(user_id, added_at desc);
create index if not exists idx_watchlist_user_updated on public.watchlist(user_id, updated_at desc);
create index if not exists idx_recent_user_viewed on public.recently_viewed(user_id, last_viewed_at desc);
create index if not exists idx_progress_user_updated on public.episode_progress(user_id, updated_at desc);
create index if not exists idx_history_user_watched on public.watch_history(user_id, watched_at desc);

alter table public.favorites enable row level security;
alter table public.watchlist enable row level security;
alter table public.app_settings enable row level security;
alter table public.search_history enable row level security;
alter table public.recently_viewed enable row level security;
alter table public.episode_progress enable row level security;
alter table public.watch_history enable row level security;

do $$
declare table_name text;
begin
  foreach table_name in array array['favorites','watchlist','app_settings','search_history','recently_viewed','episode_progress','watch_history'] loop
    execute format('drop policy if exists %I on public.%I', table_name || '_select_own', table_name);
    execute format('drop policy if exists %I on public.%I', table_name || '_insert_own', table_name);
    execute format('drop policy if exists %I on public.%I', table_name || '_update_own', table_name);
    execute format('drop policy if exists %I on public.%I', table_name || '_delete_own', table_name);
    execute format('create policy %I on public.%I for select to authenticated using ((select auth.uid()) is not null and (select auth.uid()) = user_id)', table_name || '_select_own', table_name);
    execute format('create policy %I on public.%I for insert to authenticated with check ((select auth.uid()) is not null and (select auth.uid()) = user_id)', table_name || '_insert_own', table_name);
    execute format('create policy %I on public.%I for update to authenticated using ((select auth.uid()) is not null and (select auth.uid()) = user_id) with check ((select auth.uid()) is not null and (select auth.uid()) = user_id)', table_name || '_update_own', table_name);
    execute format('create policy %I on public.%I for delete to authenticated using ((select auth.uid()) is not null and (select auth.uid()) = user_id)', table_name || '_delete_own', table_name);
  end loop;
end $$;
