import type Database from "better-sqlite3";
import type { EpisodeProgress, ProviderId, PlaybackLanguage, WatchHistoryEntry } from "../types/progress.types.js";

const progressSelect = `anilist_id AS anilistId, mal_id AS malId, episode_number AS episodeNumber, total_episodes AS totalEpisodes, COALESCE(title, '') AS title, cover_image AS coverImage, genres, "current_time" AS currentTime, duration, percentage, completed, provider_id AS providerId, language, first_watched_at AS firstWatchedAt, COALESCE(last_watched_at, updated_at) AS lastWatchedAt, completed_at AS completedAt`;
const historySelect = `id, anilist_id AS anilistId, episode_number AS episodeNumber, title, cover_image AS coverImage, progress_percentage AS progressPercentage, completed, provider_id AS providerId, language, watched_at AS watchedAt`;
export type ProgressInput = { anilistId: number; malId?: number | null; episodeNumber: number; totalEpisodes?: number | null; title: string; coverImage?: string | null; genres?: string[]; currentTime: number; duration: number; providerId?: ProviderId | null; language?: PlaybackLanguage | null; completed: boolean; };

export class PlaybackRepository {
  constructor(private readonly db: Database.Database) {}
  getAll(): EpisodeProgress[] { return this.db.prepare(`SELECT ${progressSelect} FROM episode_progress ORDER BY COALESCE(last_watched_at, updated_at) DESC`).all().map((row) => this.mapProgress(row as Record<string, unknown>)); }
  getAnime(anilistId: number): EpisodeProgress[] { return this.db.prepare(`SELECT ${progressSelect} FROM episode_progress WHERE anilist_id = ? ORDER BY episode_number`).all(anilistId).map((row) => this.mapProgress(row as Record<string, unknown>)); }
  getEpisode(anilistId: number, episodeNumber: number): EpisodeProgress | null { const row = this.db.prepare(`SELECT ${progressSelect} FROM episode_progress WHERE anilist_id = ? AND episode_number = ?`).get(anilistId, episodeNumber) as Record<string, unknown> | undefined; return row ? this.mapProgress(row) : null; }
  upsert(input: ProgressInput): EpisodeProgress { const existing = this.getEpisode(input.anilistId, input.episodeNumber); const completed = Boolean(existing?.completed || input.completed); this.db.prepare(`INSERT INTO episode_progress (anilist_id, mal_id, episode_number, total_episodes, title, cover_image, current_time, duration, percentage, completed, provider_id, language, first_watched_at, last_watched_at, completed_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ?, CURRENT_TIMESTAMP) ON CONFLICT(anilist_id, episode_number) DO UPDATE SET total_episodes=excluded.total_episodes, mal_id=excluded.mal_id, title=excluded.title, cover_image=excluded.cover_image, current_time=excluded.current_time, duration=excluded.duration, percentage=excluded.percentage, completed=?, provider_id=excluded.provider_id, language=excluded.language, last_watched_at=CURRENT_TIMESTAMP, completed_at=CASE WHEN ? = 1 THEN COALESCE(episode_progress.completed_at, CURRENT_TIMESTAMP) ELSE episode_progress.completed_at END, updated_at=CURRENT_TIMESTAMP`).run(input.anilistId, input.malId ?? null, input.episodeNumber, input.totalEpisodes ?? null, input.title, input.coverImage ?? null, input.currentTime, input.duration, Math.max(0, Math.min(100, input.duration > 0 ? input.currentTime / input.duration * 100 : 0)), completed ? 1 : 0, input.providerId ?? null, input.language ?? null, completed ? new Date().toISOString() : null, completed ? 1 : 0, completed ? 1 : 0); this.db.prepare("UPDATE episode_progress SET genres=? WHERE anilist_id=? AND episode_number=?").run(JSON.stringify(input.genres ?? []), input.anilistId, input.episodeNumber); return this.getEpisode(input.anilistId, input.episodeNumber)!; }
  removeEpisode(anilistId: number, episodeNumber: number): boolean { return this.db.prepare("DELETE FROM episode_progress WHERE anilist_id = ? AND episode_number = ?").run(anilistId, episodeNumber).changes > 0; }
  removeAnime(anilistId: number): number { return this.db.prepare("DELETE FROM episode_progress WHERE anilist_id = ?").run(anilistId).changes; }
  continueWatching(limit = 20): EpisodeProgress[] { return this.db.prepare(`SELECT ${progressSelect} FROM episode_progress WHERE completed = 0 AND current_time >= 30 AND duration > 0 ORDER BY COALESCE(last_watched_at, updated_at) DESC LIMIT ?`).all(Math.min(Math.max(limit, 1), 50)).map((row) => this.mapProgress(row as Record<string, unknown>)); }
  recentlyCompleted(limit = 20): EpisodeProgress[] { return this.db.prepare(`SELECT ${progressSelect} FROM episode_progress WHERE completed = 1 AND total_episodes IS NOT NULL AND total_episodes > 0 AND episode_number = total_episodes AND anilist_id IN (SELECT anilist_id FROM episode_progress WHERE completed = 1 GROUP BY anilist_id HAVING COUNT(*) >= MAX(total_episodes)) ORDER BY COALESCE(completed_at, updated_at) DESC LIMIT ?`).all(Math.min(Math.max(limit, 1), 50)).map((row) => this.mapProgress(row as Record<string, unknown>)); }
  recordHistory(input: ProgressInput): WatchHistoryEntry { const percentage = Math.max(0, Math.min(100, input.duration > 0 ? input.currentTime / input.duration * 100 : 0)); const existing = this.db.prepare("SELECT id FROM watch_history WHERE anilist_id = ? AND episode_number = ? ORDER BY id DESC LIMIT 1").get(input.anilistId, input.episodeNumber) as { id: number } | undefined; if (existing) this.db.prepare("UPDATE watch_history SET title=?, cover_image=?, progress_percentage=?, completed=?, provider_id=?, language=?, watched_at=CURRENT_TIMESTAMP, updated_at=CURRENT_TIMESTAMP WHERE id=?").run(input.title, input.coverImage ?? null, percentage, input.completed ? 1 : 0, input.providerId ?? null, input.language ?? null, existing.id); else this.db.prepare("INSERT INTO watch_history (anilist_id, episode_number, title, cover_image, progress_percentage, completed, provider_id, language) VALUES (?, ?, ?, ?, ?, ?, ?, ?)").run(input.anilistId, input.episodeNumber, input.title, input.coverImage ?? null, percentage, input.completed ? 1 : 0, input.providerId ?? null, input.language ?? null); this.db.prepare("UPDATE watch_history SET genres=?,mal_id=?,total_episodes=? WHERE anilist_id=? AND episode_number=?").run(JSON.stringify(input.genres ?? []),input.malId??null,input.totalEpisodes??null,input.anilistId,input.episodeNumber); return this.db.prepare(`SELECT ${historySelect} FROM watch_history WHERE anilist_id = ? AND episode_number = ? ORDER BY id DESC LIMIT 1`).get(input.anilistId, input.episodeNumber) as WatchHistoryEntry; }
  getHistory(limit = 100): WatchHistoryEntry[] { return this.db.prepare(`SELECT ${historySelect} FROM watch_history ORDER BY watched_at DESC, id DESC LIMIT ?`).all(Math.min(Math.max(limit, 1), 250)) as WatchHistoryEntry[]; }
  removeHistory(id: number): boolean { return this.db.prepare("DELETE FROM watch_history WHERE id = ?").run(id).changes > 0; }
  clearHistory(): number { return this.db.prepare("DELETE FROM watch_history").run().changes; }
  private mapProgress(row: Record<string, unknown>): EpisodeProgress { return { ...row, genres: JSON.parse(String(row.genres ?? "[]")), completed: Boolean(row.completed) } as EpisodeProgress; }
}
