import type { Pool } from "pg";
import type { AnimeSnapshotInput, Favorite, RecentlyViewed, SearchHistoryItem, WatchlistItem, WatchlistStatus } from "../types/library.types.js";
import type { EpisodeProgress, WatchHistoryEntry } from "../types/progress.types.js";
import type { ProgressInput } from "./playback.repository.js";
import type { UserLibraryRepository, UserPlaybackRepository } from "./repository.contracts.js";

const snapshotSelect = `id, anilist_id AS "anilistId", mal_id AS "malId", title, title_romaji AS "titleRomaji", cover_image AS "coverImage", banner_image AS "bannerImage", format, season_year AS "seasonYear", average_score AS "averageScore", genres`;
const snapshotValues = (input: AnimeSnapshotInput) => [input.anilistId, input.malId ?? null, input.title, input.titleRomaji ?? null, input.coverImage ?? null, input.bannerImage ?? null, input.format ?? null, input.seasonYear ?? null, input.averageScore ?? null, JSON.stringify(input.genres ?? [])];
const progressSelect = `anilist_id AS "anilistId", mal_id AS "malId", episode_number AS "episodeNumber", total_episodes AS "totalEpisodes", title, cover_image AS "coverImage", genres, current_time_seconds AS "currentTime", duration, percentage, completed, provider_id AS "providerId", language, first_watched_at AS "firstWatchedAt", last_watched_at AS "lastWatchedAt", completed_at AS "completedAt"`;
const historySelect = `id, anilist_id AS "anilistId", mal_id AS "malId", episode_number AS "episodeNumber", total_episodes AS "totalEpisodes", title, cover_image AS "coverImage", genres, progress_percentage AS "progressPercentage", completed, provider_id AS "providerId", language, watched_at AS "watchedAt"`;
const cap = (value: number | undefined, fallback: number, max: number) => Math.min(Math.max(value ?? fallback, 1), max);

export class PostgresUserLibraryRepository implements UserLibraryRepository {
  private readonly pool: Pick<Pool, "query">;
  constructor(pool: Pool) {
    this.pool = { query: (async (...args: unknown[]) => {
      const result = await (pool.query as Function).apply(pool, args);
      result.rows = result.rows.map((row: Record<string, unknown>) => Object.fromEntries(Object.entries(row).map(([key, value]) => [key,
        value instanceof Date ? value.toISOString() :
        (key === "id" || key === "averageScore") && typeof value === "string" ? Number(value) : value
      ])));
      return result;
    }) as Pool["query"] };
  }
  async favorites(userId: string) { return (await this.pool.query(`SELECT ${snapshotSelect}, added_at AS "addedAt" FROM favorites WHERE user_id=$1 ORDER BY added_at DESC,id DESC`, [userId])).rows as Favorite[]; }
  async favorite(userId: string, animeId: number) { return ((await this.pool.query(`SELECT ${snapshotSelect}, added_at AS "addedAt" FROM favorites WHERE user_id=$1 AND anilist_id=$2`, [userId, animeId])).rows[0] as Favorite | undefined) ?? null; }
  async saveFavorite(userId: string, input: AnimeSnapshotInput) { await this.pool.query(`INSERT INTO favorites(user_id,anilist_id,mal_id,title,title_romaji,cover_image,banner_image,format,season_year,average_score,genres) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::jsonb) ON CONFLICT(user_id,anilist_id) DO UPDATE SET mal_id=excluded.mal_id,title=excluded.title,title_romaji=excluded.title_romaji,cover_image=excluded.cover_image,banner_image=excluded.banner_image,format=excluded.format,season_year=excluded.season_year,average_score=excluded.average_score,genres=excluded.genres`, [userId, ...snapshotValues(input)]); return (await this.favorite(userId, input.anilistId))!; }
  async removeFavorite(userId: string, animeId: number) { return (await this.pool.query("DELETE FROM favorites WHERE user_id=$1 AND anilist_id=$2", [userId, animeId])).rowCount! > 0; }
  async watchlist(userId: string, status?: WatchlistStatus) { const values: unknown[] = [userId]; const filter = status ? " AND status=$2" : ""; if (status) values.push(status); return (await this.pool.query(`SELECT ${snapshotSelect},status,notes,added_at AS "addedAt",updated_at AS "updatedAt" FROM watchlist WHERE user_id=$1${filter} ORDER BY updated_at DESC,id DESC`, values)).rows as WatchlistItem[]; }
  async watchlistItem(userId: string, animeId: number) { return ((await this.pool.query(`SELECT ${snapshotSelect},status,notes,added_at AS "addedAt",updated_at AS "updatedAt" FROM watchlist WHERE user_id=$1 AND anilist_id=$2`, [userId, animeId])).rows[0] as WatchlistItem | undefined) ?? null; }
  async saveWatchlist(userId: string, input: AnimeSnapshotInput, status: WatchlistStatus) { await this.pool.query(`INSERT INTO watchlist(user_id,anilist_id,mal_id,title,title_romaji,cover_image,banner_image,format,season_year,average_score,genres,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::jsonb,$12) ON CONFLICT(user_id,anilist_id) DO UPDATE SET mal_id=excluded.mal_id,title=excluded.title,title_romaji=excluded.title_romaji,cover_image=excluded.cover_image,banner_image=excluded.banner_image,format=excluded.format,season_year=excluded.season_year,average_score=excluded.average_score,genres=excluded.genres,status=excluded.status,updated_at=now()`, [userId, ...snapshotValues(input), status]); return (await this.watchlistItem(userId, input.anilistId))!; }
  async updateWatchlist(userId: string, animeId: number, status: WatchlistStatus) { await this.pool.query("UPDATE watchlist SET status=$3,updated_at=now() WHERE user_id=$1 AND anilist_id=$2", [userId, animeId, status]); return this.watchlistItem(userId, animeId); }
  async removeWatchlist(userId: string, animeId: number) { return (await this.pool.query("DELETE FROM watchlist WHERE user_id=$1 AND anilist_id=$2", [userId, animeId])).rowCount! > 0; }
  async recentlyViewed(userId: string, limit = 250) { return (await this.pool.query(`SELECT ${snapshotSelect},last_viewed_at AS "lastViewedAt",view_count AS "viewCount" FROM recently_viewed WHERE user_id=$1 ORDER BY last_viewed_at DESC,id DESC LIMIT $2`, [userId, cap(limit, 250, 250)])).rows as RecentlyViewed[]; }
  async recordViewed(userId: string, input: AnimeSnapshotInput) { const result = await this.pool.query(`INSERT INTO recently_viewed(user_id,anilist_id,mal_id,title,title_romaji,cover_image,banner_image,format,season_year,average_score,genres) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::jsonb) ON CONFLICT(user_id,anilist_id) DO UPDATE SET mal_id=excluded.mal_id,title=excluded.title,title_romaji=excluded.title_romaji,cover_image=excluded.cover_image,banner_image=excluded.banner_image,format=excluded.format,season_year=excluded.season_year,average_score=excluded.average_score,genres=excluded.genres,last_viewed_at=now(),view_count=recently_viewed.view_count+1 RETURNING ${snapshotSelect},last_viewed_at AS "lastViewedAt",view_count AS "viewCount"`, [userId, ...snapshotValues(input)]); return result.rows[0] as RecentlyViewed; }
  async removeViewed(userId: string, animeId: number) { return (await this.pool.query("DELETE FROM recently_viewed WHERE user_id=$1 AND anilist_id=$2", [userId, animeId])).rowCount! > 0; }
  async clearViewed(userId: string) { return (await this.pool.query("DELETE FROM recently_viewed WHERE user_id=$1", [userId])).rowCount ?? 0; }
  async searches(userId: string, limit = 20) { return (await this.pool.query(`SELECT id,query,searched_at AS "searchedAt" FROM search_history WHERE user_id=$1 ORDER BY searched_at DESC,id DESC LIMIT $2`, [userId, cap(limit, 20, 100)])).rows as SearchHistoryItem[]; }
  async saveSearch(userId: string, query: string) { const normalized = query.trim().replace(/\s+/g, " "); const result = await this.pool.query(`INSERT INTO search_history(user_id,query,normalized_query) VALUES($1,$2::text,lower($2::text)) ON CONFLICT(user_id,normalized_query) DO UPDATE SET query=excluded.query,searched_at=now() RETURNING id,query,searched_at AS "searchedAt"`, [userId, normalized]); return result.rows[0] as SearchHistoryItem; }
  async removeSearch(userId: string, id: number) { return (await this.pool.query("DELETE FROM search_history WHERE user_id=$1 AND id=$2", [userId, id])).rowCount! > 0; }
  async clearSearches(userId: string) { return (await this.pool.query("DELETE FROM search_history WHERE user_id=$1", [userId])).rowCount ?? 0; }
  async settings(userId: string) { const defaults={theme:"dark",title_preference:"english",reduced_motion:"false",show_adult_content:"false",default_list_status:"PLANNING",default_audio_language:"sub",autoplay:"false",auto_next:"true",default_provider:"cinextream"};for(const[key,value]of Object.entries(defaults))await this.pool.query("INSERT INTO app_settings(user_id,key,value) VALUES($1,$2,$3) ON CONFLICT(user_id,key) DO NOTHING",[userId,key,value]);const rows = (await this.pool.query("SELECT key,value FROM app_settings WHERE user_id=$1 ORDER BY key", [userId])).rows as Array<{key:string;value:string}>; return Object.fromEntries(rows.map(({ key, value }) => [key, value])); }
  async setting(userId: string, key: string) { return ((await this.pool.query("SELECT value FROM app_settings WHERE user_id=$1 AND key=$2", [userId,key])).rows[0] as {value:string}|undefined)?.value ?? null; }
  async saveSetting(userId: string, key: string, value: string) { await this.pool.query("INSERT INTO app_settings(user_id,key,value) VALUES($1,$2,$3) ON CONFLICT(user_id,key) DO UPDATE SET value=excluded.value,updated_at=now()", [userId,key,value]); return value; }
}

export class PostgresUserPlaybackRepository implements UserPlaybackRepository {
  private readonly pool: Pick<Pool, "query">;
  constructor(pool: Pool) {
    this.pool = { query: (async (...args: unknown[]) => {
      const result = await (pool.query as Function).apply(pool, args);
      result.rows = result.rows.map((row: Record<string, unknown>) => Object.fromEntries(Object.entries(row).map(([key, value]) => [key,
        value instanceof Date ? value.toISOString() :
        (key === "id" || key === "averageScore") && typeof value === "string" ? Number(value) : value
      ])));
      return result;
    }) as Pool["query"] };
  }
  async allProgress(userId:string){return(await this.pool.query(`SELECT ${progressSelect} FROM episode_progress WHERE user_id=$1 ORDER BY last_watched_at DESC`,[userId])).rows as EpisodeProgress[];}
  async animeProgress(userId: string, animeId: number) { return (await this.pool.query(`SELECT ${progressSelect} FROM episode_progress WHERE user_id=$1 AND anilist_id=$2 ORDER BY episode_number`,[userId,animeId])).rows as EpisodeProgress[]; }
  async episodeProgress(userId: string, animeId: number, episode: number) { return ((await this.pool.query(`SELECT ${progressSelect} FROM episode_progress WHERE user_id=$1 AND anilist_id=$2 AND episode_number=$3`,[userId,animeId,episode])).rows[0] as EpisodeProgress|undefined) ?? null; }
  async saveProgress(userId: string, input: ProgressInput) { const prior=await this.episodeProgress(userId,input.anilistId,input.episodeNumber); const completed=Boolean(prior?.completed||input.completed); const percentage=Math.max(0,Math.min(100,input.currentTime/input.duration*100)); const result=await this.pool.query(`INSERT INTO episode_progress(user_id,anilist_id,mal_id,episode_number,total_episodes,title,cover_image,genres,current_time_seconds,duration,percentage,completed,provider_id,language,completed_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9,$10,$11,$12,$13,$14,CASE WHEN $12 THEN now() ELSE null END) ON CONFLICT(user_id,anilist_id,episode_number) DO UPDATE SET mal_id=excluded.mal_id,total_episodes=excluded.total_episodes,title=excluded.title,cover_image=excluded.cover_image,genres=excluded.genres,current_time_seconds=excluded.current_time_seconds,duration=excluded.duration,percentage=excluded.percentage,completed=episode_progress.completed OR excluded.completed,provider_id=excluded.provider_id,language=excluded.language,last_watched_at=now(),completed_at=CASE WHEN episode_progress.completed OR excluded.completed THEN coalesce(episode_progress.completed_at,now()) ELSE null END,updated_at=now() RETURNING ${progressSelect}`,[userId,input.anilistId,input.malId??null,input.episodeNumber,input.totalEpisodes??null,input.title,input.coverImage??null,JSON.stringify(input.genres??[]),input.currentTime,input.duration,percentage,completed,input.providerId??null,input.language??null]); return result.rows[0] as EpisodeProgress; }
  async removeEpisodeProgress(userId:string,id:number,ep:number){return(await this.pool.query("DELETE FROM episode_progress WHERE user_id=$1 AND anilist_id=$2 AND episode_number=$3",[userId,id,ep])).rowCount!>0;}
  async removeAnimeProgress(userId:string,id:number){return(await this.pool.query("DELETE FROM episode_progress WHERE user_id=$1 AND anilist_id=$2",[userId,id])).rowCount??0;}
  async continueWatching(userId:string,limit=20){return(await this.pool.query(`SELECT ${progressSelect} FROM episode_progress WHERE user_id=$1 AND completed=false AND current_time_seconds>=30 AND duration>0 ORDER BY last_watched_at DESC LIMIT $2`,[userId,cap(limit,20,50)])).rows as EpisodeProgress[];}
  async recentlyCompleted(userId:string,limit=20){return(await this.pool.query(`SELECT ${progressSelect} FROM episode_progress p WHERE user_id=$1 AND completed=true AND total_episodes>0 AND episode_number=total_episodes AND (SELECT count(*) FROM episode_progress x WHERE x.user_id=p.user_id AND x.anilist_id=p.anilist_id AND x.completed=true)>=p.total_episodes ORDER BY completed_at DESC LIMIT $2`,[userId,cap(limit,20,50)])).rows as EpisodeProgress[];}
  async saveHistory(userId:string,input:ProgressInput){const percentage=Math.max(0,Math.min(100,input.currentTime/input.duration*100));const result=await this.pool.query(`INSERT INTO watch_history(user_id,anilist_id,mal_id,episode_number,total_episodes,title,cover_image,genres,progress_percentage,completed,provider_id,language) VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9,$10,$11,$12) ON CONFLICT(user_id,anilist_id,episode_number) DO UPDATE SET mal_id=excluded.mal_id,total_episodes=excluded.total_episodes,title=excluded.title,cover_image=excluded.cover_image,genres=excluded.genres,progress_percentage=excluded.progress_percentage,completed=watch_history.completed OR excluded.completed,provider_id=excluded.provider_id,language=excluded.language,watched_at=now(),updated_at=now() RETURNING ${historySelect}`,[userId,input.anilistId,input.malId??null,input.episodeNumber,input.totalEpisodes??null,input.title,input.coverImage??null,JSON.stringify(input.genres??[]),percentage,input.completed,input.providerId??null,input.language??null]);return result.rows[0] as WatchHistoryEntry;}
  async history(userId:string,limit=100){return(await this.pool.query(`SELECT ${historySelect} FROM watch_history WHERE user_id=$1 ORDER BY watched_at DESC,id DESC LIMIT $2`,[userId,cap(limit,100,250)])).rows as WatchHistoryEntry[];}
  async removeHistory(userId:string,id:number){return(await this.pool.query("DELETE FROM watch_history WHERE user_id=$1 AND id=$2",[userId,id])).rowCount!>0;}
  async clearHistory(userId:string){return(await this.pool.query("DELETE FROM watch_history WHERE user_id=$1",[userId])).rowCount??0;}
}
