import Database from 'better-sqlite3';
import request from 'supertest';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { initializeDatabase } from '../src/database/connection.js';
import { createUserRepositories } from '../src/repositories/repositoryFactory.js';
import { createApp } from '../src/app.js';
import { HomeService } from '../src/services/home.service.js';
import { RecommendationService } from '../src/services/recommendation.service.js';
import { env } from '../src/utils/env.js';
import { catalog, now, summary } from './recommendation.fixtures.js';
const original = { ...env }, dbs: Database.Database[] = [];
afterEach(() => { Object.assign(env, original); dbs.forEach(d => d.close()); dbs.length = 0; });
function setup() { env.AUTH_MODE = 'local'; env.DATABASE_MODE = 'sqlite'; const db = new Database(':memory:'); dbs.push(db); initializeDatabase(db); const r = createUserRepositories(db), c = catalog(), rec = new RecommendationService(c, r, () => now), service = new HomeService(r, rec); return { r, c, rec, service, app: () => createApp({ database: db, repositories: r, animeService: c }) }; }
describe('compact, isolated Home composition', () => {
  it('returns honest cold start, no fabricated greeting, and compact bounded summaries', async () => { const { app } = setup(); const h = await request(app()).get('/api/home'); expect(h.status).toBe(200); expect(h.headers['cache-control']).toBe('no-store'); expect(h.body.data.profile.data.displayName).toBeNull(); expect(h.body.data.personalized.data.audience).toBe('cold'); expect(h.body.data.personalized.data.recommendations.length).toBeLessThanOrEqual(10); expect(h.body.data.personalized.data.recommendations[0].anime).not.toHaveProperty('description'); expect(JSON.stringify(h.body)).not.toMatch(/userId|email/); });
  it('gives local profile greeting, progress and completed actual history', async () => { const { r, service } = setup(); await r.profile!.updateProfile('local', { displayName: 'தமிழ்', avatarId: 'avatar-01' }); await r.playback.saveProgress('local', { anilistId: 8, title: 'Resume', episodeNumber: 2, currentTime: 50, duration: 100, completed: false }); await r.playback.saveProgress('local', { anilistId: 9, title: 'Completed', episodeNumber: 1, totalEpisodes: 1, currentTime: 100, duration: 100, completed: true }); const h = await service.get('local'); expect(h.profile?.data?.displayName).toBe('தமிழ்'); expect(h.continueWatching?.data?.[0]).toMatchObject({ anilistId: 8, percentage: 50 }); expect(h.recentlyCompleted?.data?.[0].anilistId).toBe(9); });
  it('isolates recommendation failure and permits a subsequent retry', async () => { const { rec, service } = setup(); const spy = vi.spyOn(rec, 'getBundle').mockRejectedValueOnce(new Error('private DB detail')); const h = await service.get('local'); expect(h.personalized.status).toBe('error'); expect(h.continueWatching?.status).toBe('ready'); expect(JSON.stringify(h)).not.toContain('private DB detail'); expect((await service.get('local')).personalized.status).toBe('ready'); spy.mockRestore(); });
  it('avoids profile/progress reload for a favorite-only invalidation', async () => { const { r, service } = setup(); const progress = vi.spyOn(r.playback, 'continueWatching'), profile = vi.spyOn(r.profile!, 'getProfile'); const h = await service.get('local', 'personalized'); expect(progress).not.toHaveBeenCalled(); expect(profile).not.toHaveBeenCalled(); expect(h.continueWatching).toBeUndefined(); expect(h.personalized.status).toBe('ready'); });
  it('deduplicates deterministic adjacent rails without consuming unrendered alternatives', async () => { const { rec, service } = setup(); const b = await rec.getBundle('local'); const rows = Array.from({ length: 30 }, (_, i) => ({ anime: summary(200+i), reason: 'Because you like Action', personalized: true })); vi.spyOn(rec, 'getBundle').mockResolvedValue({ ...b, recommendations: rows, continuations: [rows[0]], because: { sourceAnime: { id: 1, title: 'Source', coverImage: null }, recommendations: rows }, genreDiscovery: { genre: 'Action', recommendations: rows }, meta: { ...b.meta, signalCount: 4 } }); const h = (await service.get('local')).personalized.data!; const ids = [h.continuations, h.recommendations, h.because!.recommendations, h.favoriteGenres!.recommendations].flat().map(r => r.anime.id); expect(new Set(ids).size).toBe(ids.length); expect(h.because!.recommendations.length).toBe(10); expect(h.favoriteGenres!.recommendations.length).toBe(9); expect(h.audience).toBe('established'); });
  it('rejects invalid scope and requires verified authentication', async () => { const { app } = setup(); expect((await request(app()).get('/api/home?scope=invalid')).status).toBe(400); env.AUTH_MODE = 'supabase'; env.SUPABASE_URL = 'https://auth.test'; env.SUPABASE_ANON_KEY = 'test-anon-key-at-least-twenty-characters'; expect((await request(app()).get('/api/home?userId=someone')).status).toBe(401); });
});
