import Database from "better-sqlite3";
import request from "supertest";
import { afterEach, describe, expect, it, vi } from "vitest";
import { createApp } from "../src/app.js";
import schema from "../src/database/schema.sql?raw";

const dbs: Database.Database[] = [];
function setup() { const db = new Database(":memory:"); db.exec(schema); dbs.push(db); const server = createApp({ database: db, animeService: { popular: async () => ({ data: [], pagination: { page: 1, perPage: 20, hasNextPage: false, total: 0 } }) } as never }); return { db, server }; }
afterEach(() => { while (dbs.length) dbs.pop()!.close(); });
const favorite = { anilistId: 1, malId: 2, title: "Fixture", titleRomaji: "Fixture", coverImage: "https://example.com/cover.jpg", bannerImage: null, format: "TV", seasonYear: 2026, averageScore: 88, genres: ["Fantasy"] };
const fullBackup = { app: "AniVerse", version: 1, favorites: [favorite], watchlist: [{ ...favorite, anilistId: 2, status: "WATCHING", notes: "next" }], settings: { title_preference: "romaji" }, searchHistory: [{ query: "Frieren", searchedAt: "2026-01-01T00:00:00Z" }], recentlyViewed: [{ ...favorite, anilistId: 3, lastViewedAt: "2026-01-02T00:00:00Z", viewCount: 2 }], episodeProgress: [{ anilistId: 4, episodeNumber: 1, totalEpisodes: 3, currentTime: 60, duration: 100, percentage: 60, title: "Progress", completed: false, providerId: "cinextream", language: "sub", genres: ["Fantasy"] }], watchHistory: [{ anilistId: 4, episodeNumber: 1, totalEpisodes: 3, title: "Progress", progressPercentage: 60, completed: false, providerId: "cinextream", language: "sub", watchedAt: "2026-01-03T00:00:00Z", genres: ["Fantasy"] }] };

describe("phase 8 insights and data management", () => {
  it("exports exactly the supported local collections", async () => { const { server } = setup(); const body = (await request(server).get("/api/data/export")).body; expect(body).toMatchObject({ app: "AniVerse", version: 1 }); expect(Object.keys(body).sort()).toEqual(["app","episodeProgress","exportedAt","favorites","recentlyViewed","searchHistory","settings","version","watchHistory","watchlist"].sort()); expect(body).not.toHaveProperty("animeCache"); });
  it("imports an empty backup", async () => { const { server } = setup(); expect((await request(server).post("/api/data/import").send({ app: "AniVerse", version: 1 })).status).toBe(200); });
  it("rejects malformed JSON and oversized payloads safely", async () => { const { server } = setup(); expect((await request(server).post("/api/data/import").set("Content-Type", "application/json").send("{bad")).status).toBe(400); expect((await request(server).post("/api/data/import").send({ app: "AniVerse", version: 1, unexpected: "x".repeat(1_100_000) })).status).toBe(413); });
  it("imports every exported collection and deduplicates merge keys", async () => { const { db, server } = setup(); expect((await request(server).post("/api/data/import").send(fullBackup)).status).toBe(200); expect((await request(server).post("/api/data/import").send(fullBackup)).status).toBe(200); for (const table of ["favorites","watchlist","search_history","recently_viewed","episode_progress","watch_history"]) expect((db.prepare(`SELECT COUNT(*) count FROM ${table}`).get() as { count: number }).count).toBe(1); expect((db.prepare("SELECT value FROM app_settings WHERE key='title_preference'").get() as { value: string }).value).toBe("romaji"); });
  it.each([
    [{ app: "Other", version: 1 }, "wrong app"], [{ app: "AniVerse", version: 2 }, "unsupported version"],
    [{ app: "AniVerse", version: 1, favorites: {} }, "non-array collection"], [{ app: "AniVerse", version: 1, favorites: [{ anilistId: -1, title: "Bad" }] }, "invalid anime id"],
    [{ app: "AniVerse", version: 1, watchlist: [{ ...favorite, status: "NOPE" }] }, "invalid status"], [{ app: "AniVerse", version: 1, settings: { unknown: "x" } }, "invalid setting"],
    [{ app: "AniVerse", version: 1, episodeProgress: [{ anilistId: 1, episodeNumber: 1, currentTime: -1, duration: 10, title: "Bad" }] }, "negative playback"],
    [{ app: "AniVerse", version: 1, watchHistory: [{ anilistId: 1, episodeNumber: 1, title: "Bad", progressPercentage: 101 }] }, "invalid percentage"]
  ])("rejects %s (%s)", async (payload) => { const { server } = setup(); expect((await request(server).post("/api/data/import").send(payload)).status).toBe(400); });
  it("rolls back all collections when a later database write fails", async () => { const { db, server } = setup(); const log = vi.spyOn(console, "error").mockImplementation(() => undefined); db.exec("CREATE TRIGGER fail_watchlist BEFORE INSERT ON watchlist BEGIN SELECT RAISE(ABORT, 'test failure'); END"); expect((await request(server).post("/api/data/import").send(fullBackup)).status).toBe(500); expect((db.prepare("SELECT COUNT(*) count FROM favorites").get() as { count: number }).count).toBe(0); log.mockRestore(); });
  it("round-trips all user state", async () => { const { server } = setup(); await request(server).post("/api/data/import").send(fullBackup); const first = (await request(server).get("/api/data/export")).body; await request(server).delete("/api/data/reset/all"); await request(server).post("/api/data/import").send(first); const second = (await request(server).get("/api/data/export")).body; const normalize = (backup: Record<string, unknown>) => { const copy = structuredClone(backup); delete copy.exportedAt; for (const key of ["favorites","watchlist","searchHistory","recentlyViewed","episodeProgress","watchHistory"]) if (Array.isArray(copy[key])) copy[key] = (copy[key] as Array<Record<string, unknown>>).map(({ id: _id, ...row }) => row); return copy; }; expect(normalize(second)).toEqual(normalize(first)); });
  it.each([["search-history","search_history"],["recently-viewed","recently_viewed"],["watch-history","watch_history"],["progress","episode_progress"],["favorites","favorites"],["watchlist","watchlist"]])("reset %s only clears %s", async (target, table) => { const { db, server } = setup(); await request(server).post("/api/data/import").send(fullBackup); await request(server).delete(`/api/data/reset/${target}`); expect((db.prepare(`SELECT COUNT(*) count FROM ${table}`).get() as { count: number }).count).toBe(0); const other = table === "favorites" ? "watchlist" : "favorites"; expect((db.prepare(`SELECT COUNT(*) count FROM ${other}`).get() as { count: number }).count).toBe(1); });
});
