import express from "express";
import request from "supertest";
import { readFileSync } from "node:fs";
import { DataType, newDb } from "pg-mem";
import type { Pool } from "pg";
import { afterEach, describe, expect, it } from "vitest";
import { env } from "../src/utils/env.js";
import { createAuthMiddleware } from "../src/middleware/auth.js";
import { errorHandler } from "../src/middleware/errorHandler.js";
import { createUserLibraryRouter } from "../src/routes/userLibrary.routes.js";
import { createCloudDataRouter } from "../src/routes/cloudData.routes.js";
import { PostgresUserLibraryRepository } from "../src/repositories/postgres.repositories.js";
import type { AuthenticatedRequest } from "../types/auth.types.js";

const originalMode = env.AUTH_MODE;
afterEach(() => { env.AUTH_MODE = originalMode; });

function setup(failOn = "") {
  const memory = newDb();
  memory.public.registerFunction({name:"trim",args:[DataType.text],returns:DataType.text,implementation:(value:string)=>value.replace(/^ +| +$/g,"")});
  memory.public.registerFunction({name:"greatest",args:[DataType.timestamptz,DataType.timestamptz],returns:DataType.timestamptz,implementation:(a:Date,b:Date)=>a>b?a:b});
  // Use the shipped logical constraints, with only local adapter substitutions.
  const schema = readFileSync(new URL("../migrations/postgres/001_user_data.sql", import.meta.url), "utf8")
    .split("create index")[0]
    .replaceAll("bigint generated by default as identity", "bigserial")
    .replaceAll("uuid", "text")
    .replaceAll(" references auth.users(id) on delete cascade", "");
  memory.public.none(schema);
  const { Pool: MemoryPool } = memory.adapters.createPg();
  const realPool = new MemoryPool();
  let snapshot: ReturnType<typeof memory.backup> | undefined;
  const calls: string[] = [];
  const query = async (sql: string, values?: unknown[]) => {
    calls.push(sql);
    if (sql === "BEGIN") { snapshot = memory.backup(); return { rows: [], rowCount: 0 }; }
    if (sql === "ROLLBACK") { snapshot?.restore(); snapshot = undefined; return { rows: [], rowCount: 0 }; }
    if (sql === "COMMIT") { snapshot = undefined; return { rows: [], rowCount: 0 }; }
    if (sql.startsWith("SELECT pg_advisory_xact_lock")) return { rows: [], rowCount: 1 };
    if (failOn && sql.includes(failOn)) throw new Error("forced collection failure");
    if(sql.endsWith(" DO NOTHING RETURNING 1")){
      // pg-mem reports a returned row for DO NOTHING conflicts. Normalize its
      // adapter metadata from actual table cardinality; PostgreSQL does not.
      const table=/^INSERT INTO (\w+)/.exec(sql)![1];
      const before=memory.public.many(`SELECT * FROM ${table}`).length;
      const result=await realPool.query(sql,values);
      result.rowCount=memory.public.many(`SELECT * FROM ${table}`).length-before;
      return result;
    }
    return realPool.query(sql, values);
  };
  const pool = { query, connect: async () => ({ query, release() {} }) } as unknown as Pool;
  env.AUTH_MODE = "supabase";
  const app = express();
  app.use(express.json());
  app.use(createAuthMiddleware(async token => token === "a" ? { id: "a" } : token === "b" ? { id: "b" } : null).requireAuth);
  app.use(createUserLibraryRouter(new PostgresUserLibraryRepository(pool)));
  app.use(createCloudDataRouter(pool));
  app.use(errorHandler);
  return { app, pool, calls, memory };
}

function backup(id = 1) {
  const anime = { anilistId: id, title: `Test ${id}`, genres: ["Fantasy"] };
  return {
    app: "AniVerse", version: 1, favorites: [anime], watchlist: [{ ...anime, status: "WATCHING" }],
    settings: { title_preference: "romaji" }, searchHistory: [{ query: `Search ${id}` }],
    recentlyViewed: [{ ...anime, viewCount: 2 }],
    episodeProgress: [{ ...anime, episodeNumber: 1, currentTime: 60, duration: 120, completed: false }],
    watchHistory: [{ ...anime, episodeNumber: 1, progressPercentage: 50, completed: false }]
  };
}
const auth = (token: string) => ({ Authorization: `Bearer ${token}` });

describe("Phase 9 single favorite privacy contract", () => {
  it("returns identical 404 errors for another owner's favorite and an unknown favorite, while the owner can read", async () => {
    const { app } = setup();
    expect((await request(app).post("/favorites").set(auth("a")).send({ anilistId: 1, title: "Private" })).status).toBe(201);
    const foreign = await request(app).get("/favorites/1").set(auth("b"));
    const unknown = await request(app).get("/favorites/999").set(auth("b"));
    expect(foreign.status).toBe(404); expect(unknown.status).toBe(404);
    expect(foreign.body).toEqual(unknown.body);
    expect(foreign.body.error.code).toBe("RESOURCE_NOT_FOUND");
    expect((await request(app).get("/favorites/1").set(auth("a"))).body.data.title).toBe("Private");
  });
  it("rejects foreign and nonexistent deletes identically, preserves the owner's row and permits owner deletion", async () => {
    const { app } = setup();
    await request(app).post("/favorites").set(auth("a")).send({ anilistId: 1, title: "Private" });
    const foreign = await request(app).delete("/favorites/1").set(auth("b"));
    const unknown = await request(app).delete("/favorites/999").set(auth("b"));
    expect(foreign.status).toBe(404); expect(unknown.status).toBe(404);
    expect(foreign.body).toEqual(unknown.body); expect(foreign.body.error.code).toBe("RESOURCE_NOT_FOUND");
    expect((await request(app).get("/favorites/1").set(auth("a"))).status).toBe(200);
    const removed = await request(app).delete("/favorites/1").set(auth("a"));
    expect(removed.status).toBe(200); expect(removed.body.data.removed).toBe(true);
    expect((await request(app).get("/favorites/1").set(auth("a"))).status).toBe(404);
  });
  it("preserves empty collection HTTP 200 semantics", async () => {
    const { app } = setup(); const response = await request(app).get("/favorites").set(auth("b"));
    expect(response.status).toBe(200); expect(response.body.data).toEqual([]);
  });
});

describe("Phase 9 cloud import duplicate accounting", () => {
  it("counts exactly seven existing logical records and updates their content", async () => {
    const { app, pool } = setup();
    const first = await request(app).post("/data/import").set(auth("a")).send(backup());
    expect(first.status).toBe(200); expect(first.body.data.duplicatesMerged).toBe(0);
    const payload = backup(); payload.favorites[0].title = "Merged title";
    const duplicate = await request(app).post("/data/import").set(auth("a")).send(payload);
    expect(duplicate.status).toBe(200); expect(duplicate.body.data.duplicatesMerged).toBe(7);
    expect((await pool.query("SELECT title FROM favorites WHERE user_id=$1", ["a"])).rows[0].title).toBe("Merged title");
    for (const table of ["favorites", "watchlist", "app_settings", "search_history", "recently_viewed", "episode_progress", "watch_history"])
      expect((await pool.query(`SELECT * FROM ${table} WHERE user_id=$1`, ["a"])).rows).toHaveLength(1);
  });
  it("counts exactly seven duplicates in a mixed fourteen-record import and inserts seven new records", async () => {
    const { app, pool } = setup(); await request(app).post("/data/import").set(auth("a")).send(backup());
    const mixed = backup(), other = backup(2);
    for (const key of ["favorites", "watchlist", "searchHistory", "recentlyViewed", "episodeProgress", "watchHistory"] as const)
      mixed[key].push(...other[key]);
    Object.assign(mixed.settings, { autoplay: "true" });
    const response = await request(app).post("/data/import").set(auth("a")).send(mixed);
    expect(response.status).toBe(200); expect(response.body.data.duplicatesMerged).toBe(7);
    for (const table of ["favorites", "watchlist", "app_settings", "search_history", "recently_viewed", "episode_progress", "watch_history"])
      expect((await pool.query(`SELECT * FROM ${table} WHERE user_id=$1`, ["a"])).rows).toHaveLength(2);
  });
  it("uses owner-scoped keys, normalized searches and episode-specific keys without double counting", async () => {
    const { app } = setup(); await request(app).post("/data/import").set(auth("a")).send(backup());
    const otherOwner = await request(app).post("/data/import").set(auth("b")).send(backup());
    expect(otherOwner.body.data.duplicatesMerged).toBe(0);
    const p = { app: "AniVerse", version: 1, favorites: [{ anilistId: 3, title: "New" }, { anilistId: 3, title: "Merged" }], searchHistory: [{ query: " SEARCH 1 " }], episodeProgress: [{ anilistId: 1, title: "Episode 2", episodeNumber: 2, currentTime: 30, duration: 120 }] };
    const response = await request(app).post("/data/import").set(auth("a")).send(p);
    expect(response.status).toBe(200); expect(response.body.data.duplicatesMerged).toBe(2);
  });
  it("rolls back updates and inserts after duplicate detection when a later collection fails", async () => {
    const { app, memory, calls } = setup("INSERT INTO watch_history");
    memory.public.none("INSERT INTO favorites(user_id,anilist_id,title) VALUES('a',1,'Original')");
    const payload = backup(); payload.favorites[0].title = "Should roll back";
    const response = await request(app).post("/data/import").set(auth("a")).send(payload);
    expect(response.status).toBe(500); expect(response.body.success).toBe(false);
    expect(response.body.data).toBeUndefined(); expect(calls).toContain("ROLLBACK"); expect(calls).not.toContain("COMMIT");
    expect(calls.some(sql=>sql.startsWith("INSERT INTO favorites")&&sql.includes(" DO UPDATE SET"))).toBe(true);
    expect(memory.public.many("SELECT title FROM favorites")).toEqual([{ title: "Original" }]);
    expect(memory.public.many("SELECT * FROM watchlist")).toEqual([]);
  });
  it("rejects ownership fields before any write", async () => {
    const { app, calls } = setup(); const p = backup();
    Object.assign(p.favorites[0], { user_id: "b", ownerId: "b", createdBy: "b" });
    const response = await request(app).post("/data/import").set(auth("a")).send(p);
    expect(response.status).toBe(400); expect(calls).toEqual([]);
  });
});
