import { describe, it, expect } from 'vitest';
import { normalizeSignals, genrePreferences, rankRecommendations, recencyMultiplier, deduplicateCandidates } from '../src/services/recommendation.engine.js';
import { empty, episode, favorite, now, stamp, summary } from './recommendation.fixtures.js';
const candidate = (id: number, genres = ['Action']) => ({ anime: summary(id, genres), similarities: [], continuations: [] });
describe('shared deterministic recommendation engine', () => {
  it('bounds 100 versus 12 episodes to equal anime-level votes', () => {
    const data = empty(); data.progress = [...Array.from({ length: 100 }, (_, i) => episode(1, i + 1)), ...Array.from({ length: 12 }, (_, i) => episode(2, i + 1, ['Comedy'], 12))];
    const signals = normalizeSignals(data, now); expect(signals).toHaveLength(2); expect(signals[0].strength).toEqual(signals[1].strength); expect(genrePreferences(signals).map(g => g.score)).toEqual([5, 5]);
  });
  it('uses the strongest signal instead of adding duplicate activity', () => { const d = empty(); d.favorites = [favorite(1)]; d.viewed = [{ ...favorite(1), lastViewedAt: stamp, viewCount: 1000 }]; d.progress = Array.from({ length: 100 }, (_, i) => episode(1, i + 1)); expect(normalizeSignals(d, now)[0].strength).toBe(6); });
  it('gives recent activity a modest bonus while retaining old taste', () => { expect(recencyMultiplier(now, now)).toBe(1.25); expect(recencyMultiplier(now - 10 * 365 * 86400000, now)).toBeGreaterThan(1); expect(recencyMultiplier(null, now)).toBe(1); });
  it('weights favorites above casual views', () => { const d = empty(); d.favorites = [favorite(1)]; d.viewed = [{ ...favorite(2), lastViewedAt: stamp, viewCount: 1 }]; const s = normalizeSignals(d, now); expect(s[0].strength).toBeGreaterThan(s[1].strength); });
  it('does not treat a single completed episode as a completed series', () => { const d = empty(); d.progress = [episode(1, 1)]; expect(normalizeSignals(d, now)[0].completed).toBe(false); });
  it('recognizes a complete series and excludes it from future picks', () => { const d = empty(); d.progress = [episode(1, 1, ['Action'], 2), episode(1, 2, ['Action'], 2)]; const s = normalizeSignals(d, now); expect(s[0].completed).toBe(true); expect(rankRecommendations(s, [candidate(1), candidate(101)], 12).map(r => r.anime.id)).toEqual([101]); });
  it('excludes owned listed watching and source titles consistently', () => { const d = empty(); d.favorites = [favorite(1)]; d.watchlist = [{ ...favorite(2), status: 'PLANNING', updatedAt: stamp, notes: null }]; d.progress = [episode(3, 1)]; expect(rankRecommendations(normalizeSignals(d, now), [1, 2, 3, 101].map(id => candidate(id)), 12).map(r => r.anime.id)).toEqual([101]); });
  it('deduplicates without multiplying similarity evidence', () => { expect(deduplicateCandidates([{ ...candidate(101), similarities: [1] }, { ...candidate(101), similarities: [1] }])).toMatchObject([{ similarities: [1] }]); });
  it('emits reasons supported by actual preference data', () => { const d = empty(); d.favorites = [favorite(1)]; const r = rankRecommendations(normalizeSignals(d, now), [candidate(101), candidate(102, ['Romance'])], 12); expect(r[0].explanation).toEqual({ type: 'genre', label: 'Because you like Action', genre: 'Action' }); expect(r.find(x => x.anime.id === 102)?.personalized).toBe(false); });
  it('prefers truthful source explanations to genre reasons', () => { const d = empty(); d.progress = [episode(1, 1)]; const r = rankRecommendations(normalizeSignals(d, now), [{ ...candidate(101), similarities: [1] }], 12); expect(r[0].reasonType).toBe('source_anime'); expect(r[0].reason).toBe('Because you watched Anime 1'); });
  it('keeps franchise continuations separate from similarity', () => { const d = empty(); d.progress = [episode(1, 1, ['Action'], 1)]; const s = normalizeSignals(d, now), c = [{ ...candidate(101), continuations: [1] }]; expect(rankRecommendations(s, c, 12)).toEqual([]); expect(rankRecommendations(s, c, 12, 'continuation')[0].reasonType).toBe('continuation'); });
  it('labels cold starts honestly and returns bounded unique results', () => { const c = Array.from({ length: 200 }, (_, i) => candidate(i + 1)); const r = rankRecommendations([], c, 500); expect(r).toHaveLength(20); expect(r.every(x => !x.personalized && x.reason === 'Popular on AniList')).toBe(true); });
  it('is deterministic with fixed time and reordered equivalent signals', () => { const d = empty(); d.favorites = [favorite(1), favorite(2, ['Comedy'])]; const r = () => rankRecommendations(normalizeSignals(d, now), [candidate(101), candidate(102, ['Comedy'])], 12); const first = r(); d.favorites.reverse(); expect(r()).toEqual(first); });
  it('normalizes SQLite genre JSON and timestamps equivalently', () => { const d = empty(); d.favorites = [favorite(1)]; const a = normalizeSignals(d, now); d.favorites = [{ ...favorite(1), genres: '["Action"]' as never, addedAt: '2026-09-14 00:00:00' }]; expect(normalizeSignals(d, now)).toEqual(a); });
  it('reduces repeated-genre spam deterministically without randomization', () => { const r = rankRecommendations([], [candidate(1), candidate(2), candidate(3, ['Comedy'])], 3); expect(r.map(x => x.anime.id)).toEqual([1, 3, 2]); });
});
