import Database from 'better-sqlite3';
import request from 'supertest';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { initializeDatabase } from '../src/database/connection.js';
import { createApp } from '../src/app.js';
import { SQLiteUserLibraryRepository, SQLiteUserPlaybackRepository } from '../src/repositories/sqlite.adapters.js';
import { RecommendationService } from '../src/services/recommendation.service.js';
import { env } from '../src/utils/env.js';
import { catalog, favorite, now, summary } from './recommendation.fixtures.js';
const dbs: Database.Database[] = [], original = { ...env };
afterEach(() => { Object.assign(env, original); while (dbs.length) dbs.pop()!.close(); });
function setup(anime = catalog()) { const db = new Database(':memory:'); initializeDatabase(db); dbs.push(db); const repositories = { library: new SQLiteUserLibraryRepository(db), playback: new SQLiteUserPlaybackRepository(db) }; return { db, repositories, service: new RecommendationService(anime, repositories, () => now), app: () => createApp({ database: db, repositories, animeService: anime }) }; }
describe('recommendation orchestration and private API', () => {
  it('shares simultaneous calculations by owner and retains reasons', async () => { let calls = 0; const { service, repositories } = setup(catalog(() => calls++)); await repositories.library.saveFavorite('local', favorite(1)); const [a, b] = await Promise.all([service.getBundle('local'), service.getBundle('local')]); expect(a).toBe(b); expect(calls).toBe(4); expect(a.recommendations[0].reasonType).toBe('favorite_similarity'); });
  it('returns honest cold-start metadata without source details traffic', async () => { const { service } = setup(); const b = await service.getBundle('local'); expect(b.metrics.catalogCalls).toBe(2); expect(b.meta.personalized).toBe(false); expect(b.recommendations.every(r => r.reasonType === 'catalog')).toBe(true); });
  it('allows partial results with explicit metadata and retries after total failure', async () => { const anime = catalog(); const fail = vi.fn().mockRejectedValue(new Error('fixture unavailable')); anime.popular = fail; const { service } = setup(anime); expect((await service.getBundle('local')).meta).toMatchObject({ partial: true, failedSources: 1 }); anime.topRated = fail; await expect(service.getBundle('local')).rejects.toMatchObject({ code: 'RECOMMENDATIONS_UNAVAILABLE' }); anime.popular = catalog().popular; expect((await service.getBundle('local')).recommendations.length).toBeGreaterThan(0); });
  it('requires authentication without trusting query ownership', async () => { const { app } = setup(); env.AUTH_MODE = 'supabase'; env.SUPABASE_URL = 'https://auth.test'; env.SUPABASE_ANON_KEY = 'test-anon-key-at-least-twenty-characters'; for (const path of ['/api/recommendations', '/api/recommendations/home', '/api/recommendations/because-you-watched', '/api/recommendations/continuations']) expect((await request(app()).get(path + '?userId=someone')).status).toBe(401); });
  it('preserves legacy arrays, bounds result limits and keeps private no-store', async () => { const { app } = setup(); const server = app(); const r = await request(server).get('/api/recommendations?limit=2&userId=untrusted'); expect(r.status).toBe(200); expect(r.headers['cache-control']).toBe('no-store'); expect(r.body.data).toHaveLength(2); expect(r.body.data[0]).toMatchObject({ anime: { id: expect.any(Number) }, reason: expect.any(String), explanation: { type: 'catalog' } }); expect((await request(server).get('/api/recommendations?limit=invalid')).status).toBe(400); expect((await request(server).get('/api/recommendations/home')).body.data.meta.personalized).toBe(false); });
  it('normalizes complete upstream failure safely through HTTP', async () => { const anime = catalog(); anime.popular = anime.topRated = async () => { throw new Error('private upstream detail'); }; const r = await request(setup(anime).app()).get('/api/recommendations'); expect(r.status).toBe(503); expect(r.body.error.code).toBe('RECOMMENDATIONS_UNAVAILABLE'); expect(JSON.stringify(r.body)).not.toContain('private upstream detail'); });
  it('keeps small and large history requests bounded and records current performance', async () => {
    for (const count of [1, 1000]) { let calls = 0; const { service, db } = setup(catalog(() => calls++)); db.prepare("INSERT INTO favorites(anilist_id,title,genres,added_at) VALUES(1,'Anime 1','[\"Action\"]','2026-09-14T00:00:00Z')").run(); const insert = db.prepare("INSERT INTO episode_progress(anilist_id,episode_number,total_episodes,title,genres,current_time,duration,percentage,completed,last_watched_at) VALUES(?,?,?,?,?,100,100,100,1,'2026-09-14T00:00:00Z')"); db.transaction(() => { for (let i = 0; i < count; i++) insert.run(Math.floor(i / 100) + 1, i % 100 + 1, 100, `Anime ${Math.floor(i / 100) + 1}`, JSON.stringify(i < 100 ? ['Action'] : ['Romance'])); })(); const b = await service.getBundle('local'); expect(calls).toBeLessThanOrEqual(6); expect(b.metrics.candidateCount).toBeLessThanOrEqual(148); expect(b.metrics.repositoryQueries).toBe(5); console.info('RECOMMENDATION_METRICS', JSON.stringify({ historyRows: count, ...b.metrics, payloadBytes: Buffer.byteLength(JSON.stringify(b.recommendations)) })); }
  });
  it('does not allow duplicate candidate appearances to increase a score', async () => { const c = catalog(); c.topRated = async () => ({ data: Array(25).fill(summary(101)), pagination: { page: 1, perPage: 25, total: 25, hasNextPage: false } }); const r = await setup(c).service.getBundle('local'); expect(new Set(r.recommendations.map(x => x.anime.id)).size).toBe(r.recommendations.length); });
  it('avoids adjacent Home duplicates while keeping the legacy discovery response intact', async () => { const { app, repositories } = setup(); await repositories.playback.saveProgress('local', { anilistId: 1, title: 'Anime 1', genres: ['Action'], episodeNumber: 1, totalEpisodes: 10, currentTime: 50, duration: 100, completed: false }); const server = app(); const legacy = (await request(server).get('/api/recommendations')).body.data; const home = (await request(server).get('/api/recommendations/home')).body.data; expect(legacy.some((r: { anime: { id: number } }) => r.anime.id === 101)).toBe(true); expect(home.because.recommendations[0].anime.id).toBe(101); expect(home.recommendations.some((r: { anime: { id: number } }) => r.anime.id === 101)).toBe(false); });
});
