import type Database from "better-sqlite3";
import type { AnimeListServiceContract } from "./anilist.service.js";
export class RecommendationService {
  constructor(private readonly anime: AnimeListServiceContract, private readonly db: Database.Database) {}
  async getRecommendations(limit = 12) { const favorites = this.db.prepare("SELECT anilist_id FROM favorites").all() as Array<{ anilist_id: number }>; const completed = new Set((this.db.prepare("SELECT anilist_id FROM episode_progress WHERE completed=1").all() as Array<{ anilist_id: number }>).map((row) => row.anilist_id)); const weights = this.genreWeights(); const favoriteIds = new Set(favorites.map((item) => item.anilist_id)); const page = await this.anime.popular(1, Math.min(Math.max(limit * 2, 12), 25)); const seen = new Set<number>(); return page.data.filter((item) => !completed.has(item.id) && !seen.has(item.id) && !favoriteIds.has(item.id)).map((anime) => { seen.add(anime.id); const match = anime.genres.reduce((sum, genre) => sum + (weights.get(genre) ?? 0), 0); return { anime, score: match + (anime.averageScore ?? 0) / 20 + (anime.popularity ? 1 : 0), reason: match > 0 ? `Because you like ${anime.genres.find((genre) => weights.has(genre))}` : "Popular with AniVerse viewers" }; }).sort((a, b) => b.score - a.score).slice(0, limit).map(({ anime, reason }) => ({ anime, reason })); }
  async getBecauseYouWatched(limit = 12) { const source = this.db.prepare("SELECT anilist_id AS id FROM episode_progress WHERE completed = 1 GROUP BY anilist_id ORDER BY MAX(COALESCE(completed_at, updated_at)) DESC LIMIT 1").get() as { id?: number } | undefined; if (!source?.id) return null; const details = await this.anime.details(source.id); const related = details.recommendations?.length ? details.recommendations : details.relatedAnime; const completed = new Set((this.db.prepare("SELECT anilist_id FROM episode_progress WHERE completed=1").all() as Array<{ anilist_id: number }>).map((row) => row.anilist_id)); const title = details.title.english ?? details.title.romaji ?? details.title.native ?? "this anime"; return { sourceAnime: { id: details.id, title, coverImage: details.coverImage.large }, recommendations: related.filter((item) => !completed.has(item.id) && item.id !== details.id).slice(0, Math.min(Math.max(limit, 1), 20)).map((anime) => ({ anime, reason: `Recommended for viewers of ${title}` })) }; }
  private genreWeights() { const weights = new Map<string, number>(); const rows = this.db.prepare("SELECT anilist_id, title FROM favorites UNION ALL SELECT anilist_id, title FROM recently_viewed UNION ALL SELECT anilist_id, title FROM watchlist").all() as Array<{ anilist_id: number; title: string }>; for (const row of rows) { const cached = this.db.prepare("SELECT payload FROM anime_cache WHERE anilist_id = ? ORDER BY cached_at DESC LIMIT 1").get(row.anilist_id) as { payload?: string } | undefined; try { const anime = cached?.payload ? JSON.parse(cached.payload) as { genres?: unknown } : null; if (Array.isArray(anime?.genres)) for (const genre of anime.genres) if (typeof genre === "string") weights.set(genre, (weights.get(genre) ?? 0) + 1); } catch { /* stale cache is ignored */ } } return weights; }
}

