import {useAuth} from "../auth/AuthContext";
import { useRef, useState } from "react";
import { Button } from "./Button";
import { apiFetch } from "../services/apiClient";

export function DataTransfer({ onImported, exportOnly = false }: { onImported?: () => void | Promise<void>; exportOnly?: boolean }) {
  const online=useAuth().mode==="supabase";
  const input = useRef<HTMLInputElement>(null); const [message, setMessage] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const exportData = async () => { setBusy(true); try { const response = await apiFetch("/api/data/export"); if (!response.ok) throw new Error(); const blob = await response.blob(); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `aniverse-backup-${new Date().toISOString().slice(0, 10)}.json`; anchor.click(); URL.revokeObjectURL(url); setMessage("Backup exported."); } catch { setMessage("Unable to export AniVerse data."); } finally { setBusy(false); } };
  const importData = async (file: File) => { if (file.size > 1024 * 1024) { setMessage("Backup is too large. Maximum size is 1 MB."); return; } setBusy(true); try { const payload: unknown = JSON.parse(await file.text()); const response = await apiFetch("/api/data/import", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); if (!response.ok) throw new Error(); const result=await response.json();await onImported?.(); setMessage(`Backup imported: ${result.data?.favoritesImported??0} favorites, ${result.data?.watchlistImported??0} list entries, ${result.data?.progressImported??0} progress records.`); } catch { setMessage("Unable to import this backup."); } finally { setBusy(false); } };
  return <div className="mt-6 border-t border-outline pt-5"><p className="text-sm font-semibold text-foreground">Data transfer</p>{online&&!exportOnly&&<p className="mt-2 text-sm text-muted">This merges data from your local AniVerse backup into your signed-in account.</p>}<div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-1"><Button variant="secondary" disabled={busy} onClick={() => void exportData()}>Export AniVerse Data</Button>{!exportOnly&&<Button variant="ghost" disabled={busy} onClick={() => input.current?.click()}>{online?"Import Local AniVerse Backup":"Import AniVerse Data"}</Button>}</div>{!exportOnly&&<input ref={input} type="file" accept="application/json,.json" className="hidden" aria-label="Choose AniVerse backup JSON" onChange={(event) => { const file = event.target.files?.[0]; if (file) void importData(file); event.target.value = ""; }} />}{message && <p className="mt-2 text-xs text-muted" role="status">{message}</p>}</div>;
}
