import {useEffect,useRef,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {Library,Trash2} from 'lucide-react';
import {AnimeGrid} from './AnimeGrid';
import {AnimeImage} from './AnimeImage';
import {Button} from './Button';
import {Drawer} from './Drawer';
import {EmptyState} from './EmptyState';
import {ErrorState} from './PageState';
import {ConfirmDialog} from './ConfirmDialog';
import {ProgressBar} from './ProgressBar';
import {useLibrary} from '../context/LibraryContext';
import {libraryQueryApi,type Collection,type LibraryPage,type LibraryEntry} from '../services/libraryQueryApi';
import {progressApi} from '../services/progressApi';
import {libraryToAnime,WATCHLIST_STATUSES,type WatchlistStatus} from '../types/library';

const labels:Record<string,string>={PLANNING:'Plan to Watch',WATCHING:'Watching',COMPLETED:'Completed',ON_HOLD:'On Hold',DROPPED:'Dropped'};
const names:Record<Collection,string>={'favorites':'favorites','watchlist':'My List','watch-history':'watch history','recently-viewed':'recently viewed anime','continue-watching':'continue watching','recently-completed':'recently completed anime'};
export function LibraryBrowser({collection}:{collection:Collection}){
 const library=useLibrary();const [url,setUrl]=useSearchParams();const [data,setData]=useState<LibraryPage|null>(null);const [busy,setBusy]=useState(true);const [error,setError]=useState(false);const [retry,setRetry]=useState(0);const [drawer,setDrawer]=useState(false);const [confirm,setConfirm]=useState(false);const [clearing,setClearing]=useState(false);const sequence=useRef(0);
 const [search,setSearch]=useState(url.get('search')??'');
 const pageSize=['12','24','48'].includes(url.get('pageSize')??'')?url.get('pageSize')!:library.settings.library_page_size??'24';
 const params=new URLSearchParams();for(const field of ['search','genre','status','sort','direction','page'])if(url.has(field))params.set(field,url.get(field)!);params.set('pageSize',pageSize);
 const key=params.toString();const view=library.settings.library_view_mode==='list'?'list':'grid';
 function change(values:Record<string,string>){setUrl(previous=>{const next=new URLSearchParams(previous);for(const[k,v]of Object.entries(values))if(v)next.set(k,v);else next.delete(k);next.delete('page');return next;});}
 useEffect(()=>{setSearch(url.get('search')??'');},[url]);
 useEffect(()=>{if(search===(url.get('search')??''))return;const timer=window.setTimeout(()=>change({search:search.trim()}),300);return()=>window.clearTimeout(timer);},[search,url]);
 useEffect(()=>{if(library.loading)return;const id=++sequence.current;const controller=new AbortController();setBusy(true);setError(false);libraryQueryApi.page(collection,new URLSearchParams(key),controller.signal).then(result=>{if(id===sequence.current){setData(result);if(result.total>0&&result.page>result.totalPages)setUrl(p=>{const n=new URLSearchParams(p);n.set("page",String(result.totalPages));return n;});}}).catch(()=>{if(!controller.signal.aborted&&id===sequence.current)setError(true);}).finally(()=>{if(id===sequence.current)setBusy(false);});return()=>controller.abort();},[collection,key,retry,library.revisions[collection],library.loading]);
 async function remove(item:LibraryEntry){try{if(collection==='watch-history')await progressApi.removeHistory(item.id!);else await library.removeHistory(item.anilistId);setRetry(v=>v+1);}catch{setError(true);}}
 const filtered=!!(url.get('search')||url.get('genre')||url.get('status'));
 const filters=(mobile:boolean)=><LibraryFilters key={mobile?'mobile':'desktop'} collection={collection} genres={data?.genres??[]} values={url} onApply={values=>{change(values);setDrawer(false);}} />;
 return <section aria-label={`${names[collection]} collection`} className="space-y-5">
  <div className="flex flex-wrap items-end gap-3"><label className="min-w-0 flex-1 text-sm font-semibold">Search library<input type="search" maxLength={100} value={search} onChange={e=>setSearch(e.target.value)} className="mt-2 w-full rounded border border-outline bg-surface p-3 focus-visible:outline-accent" placeholder="Search stored anime titles" /></label><Button variant="secondary" className="lg:hidden" onClick={()=>setDrawer(true)}>Filters</Button>
   <fieldset className="flex gap-2"><legend className="sr-only">Library view</legend>{(['grid','list'] as const).map(mode=><button key={mode} type="button" aria-pressed={view===mode} onClick={()=>void library.updateSetting('library_view_mode',mode)} className={`rounded border px-3 py-3 capitalize focus-visible:outline focus-visible:outline-2 focus-visible:outline-accent ${view===mode?"border-accent bg-accent/15":"border-outline"}`}>{view===mode&&<span aria-hidden="true">? </span>}{mode}</button>)}</fieldset>
   <label className="text-sm">Items per page<select value={pageSize} onChange={e=>{change({pageSize:e.target.value});void library.updateSetting('library_page_size',e.target.value);}} className="ml-2 rounded border border-outline bg-surface p-3">{[12,24,48].map(n=><option key={n}>{n}</option>)}</select></label>
  </div><div className="hidden lg:block">{filters(false)}</div><Drawer open={drawer} onClose={()=>setDrawer(false)} title="Library filters">{drawer&&filters(true)}</Drawer>
  <div className="flex flex-wrap items-center justify-between gap-3"><p role="status" aria-live="polite" className="text-sm text-muted">{busy?'Updating library…':`${data?.total??0} results`}</p>{filtered&&<Button variant="ghost" onClick={()=>{setSearch('');change({search:'',genre:'',status:'',sort:'',direction:''});}}>Reset filters</Button>}{(collection==='watch-history'||collection==='recently-viewed')&&!!data?.total&&<Button variant="ghost" onClick={()=>setConfirm(true)}>Clear {names[collection]}</Button>}</div>
  {error?<ErrorState message={`Unable to load ${names[collection]}.`} onRetry={()=>setRetry(v=>v+1)} />:!data&&busy?<AnimeGrid anime={[]} loading announceLoading={false} />:data?.items.length===0?<EmptyState icon={Library} title={filtered?`No ${names[collection]} match these filters`:collection==='favorites'?'No favorites yet':collection==='watch-history'?'No watch history yet':collection==='recently-viewed'?'No recently viewed anime':'Your anime list is empty'} description={filtered?'Try another search or reset the filters.':'Saved anime and meaningful playback activity appear here.'} action={<Button to="/browse">Explore anime</Button>} />:<div aria-busy={busy} className={busy?'opacity-70':''}>
   {view==='grid'&&['favorites','watchlist','recently-viewed'].includes(collection)?<AnimeGrid anime={(data?.items??[]).map(libraryToAnime)} />:<div className="space-y-3">{data?.items.map(item=><LibraryRow key={`${item.anilistId}-${item.episodeNumber??0}-${item.id??0}`} item={item} collection={collection} onRemove={()=>void remove(item)} onStatus={status=>void library.updateWatchlist(item.anilistId,status)} />)}</div>}
  </div>}
  {!!data?.totalPages&&<nav aria-label="Library pagination" className="flex items-center justify-center gap-4"><Button variant="secondary" disabled={busy||data.page<=1} onClick={()=>setUrl(p=>{const n=new URLSearchParams(p);n.set('page',String(data.page-1));return n;})}>Previous</Button><span>Page {data.page} of {data.totalPages}</span><Button variant="secondary" disabled={busy||data.page>=data.totalPages} onClick={()=>setUrl(p=>{const n=new URLSearchParams(p);n.set('page',String(data.page+1));return n;})}>Next</Button></nav>}
  {confirm&&<ConfirmDialog title={`Clear ${names[collection]}?`} description={collection==='watch-history'?'Playback activity will be removed. Episode progress remains.':'Details-page history will be removed. Playback activity remains.'} confirmLabel="Clear history" danger loading={clearing} onCancel={()=>setConfirm(false)} onConfirm={async()=>{setClearing(true);try{if(collection==='watch-history')await progressApi.clearHistory();else await library.clearHistory();setConfirm(false);setRetry(v=>v+1);}catch{setError(true);}finally{setClearing(false);}}} />}
 </section>;
}
function LibraryFilters({collection,genres,values,onApply}:{collection:Collection;genres:string[];values:URLSearchParams;onApply:(v:Record<string,string>)=>void}){
 const [genre,setGenre]=useState(values.get('genre')??'');const [status,setStatus]=useState(values.get('status')??'');const [sort,setSort]=useState(`${values.get('sort')??'date'}:${values.get('direction')??'desc'}`);
 useEffect(()=>{setGenre(values.get('genre')??'');setStatus(values.get('status')??'');setSort(`${values.get('sort')??'date'}:${values.get('direction')??'desc'}`);},[values]);
 const selectClass='mt-2 w-full rounded border border-outline bg-surface p-3';
 return <form onSubmit={e=>{e.preventDefault();const [field,direction]=sort.split(':');onApply({genre,status,sort:field,direction});}} className="grid gap-3 lg:grid-cols-4"><label className="text-sm">Genre<select aria-label="Genre" className={selectClass} value={genre} onChange={e=>setGenre(e.target.value)}><option value="">All genres</option>{genres.map(g=><option key={g}>{g}</option>)}</select></label>
  {collection==='watchlist'&&<label className="text-sm">Status<select aria-label="Status" className={selectClass} value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{WATCHLIST_STATUSES.map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></label>}
  <label className="text-sm">Sort<select aria-label="Sort" className={selectClass} value={sort} onChange={e=>setSort(e.target.value)}><option value="date:desc">Most recent</option><option value="date:asc">Oldest first</option><option value="title:asc">Title A–Z</option><option value="title:desc">Title Z–A</option>{['favorites','watchlist','recently-viewed'].includes(collection)&&<><option value="score:desc">Score high–low</option><option value="year:desc">Year newest</option><option value="year:asc">Year oldest</option></>}</select></label><Button type="submit" variant="secondary" className="self-end">Apply filters</Button></form>;
}
function LibraryRow({item,collection,onRemove,onStatus}:{item:LibraryEntry;collection:Collection;onRemove:()=>void;onStatus:(s:WatchlistStatus)=>void}){
 const playback=item.episodeNumber!==undefined;const date=item.date??item.watchedAt??item.lastWatchedAt;
 return <article className="flex min-w-0 items-center gap-3 rounded border border-outline bg-surface p-3"><Link to={`/anime/${item.anilistId}`} className="shrink-0"><AnimeImage src={item.coverImage} alt={`${item.title} cover`} className="h-24 w-16 rounded object-cover" /></Link><div className="min-w-0 flex-1"><h3><Link to={`/anime/${item.anilistId}`} className="break-words font-bold text-foreground hover:text-accent">{item.title}</Link></h3><p className="mt-1 text-xs text-muted">{[item.seasonYear,item.format,item.averageScore!=null?`Score ${item.averageScore}`:null].filter(v=>v!=null).join(' · ')}</p>{date&&<p className="text-xs text-muted">{new Date(date).toLocaleDateString()}{item.viewCount!=null?` ? ${item.viewCount} views`:null}</p>}
  {playback&&<><p className="text-sm">Episode {item.episodeNumber}{item.currentTime!=null?` · Resume at ${Math.floor(item.currentTime/60)}:${String(Math.floor(item.currentTime%60)).padStart(2,'0')}`:''}{item.completed?' · Completed':''}</p><ProgressBar value={item.percentage??0} label={`${item.title} episode progress`} /><Link to={`/watch/${item.anilistId}/${item.episodeNumber}`} className="text-sm font-bold text-accent">{item.completed?'Watch again':'Resume'}</Link></>}
  {collection==='watchlist'&&<label className="text-xs">Watch status<select aria-label={`Status for ${item.title}`} value={item.status} onChange={e=>onStatus(e.target.value as WatchlistStatus)} className="ml-2 mt-2 max-w-full rounded border border-outline bg-surface p-2">{WATCHLIST_STATUSES.map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></label>}</div>{['watch-history','recently-viewed'].includes(collection)&&<Button variant="ghost" aria-label={`Remove ${item.title} from ${names[collection]}`} onClick={onRemove}><Trash2 size={16} /></Button>}</article>;
}
